### ISSUE TITLE
QoS and FIO/json_config hangs

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1146]
While working on adding json_config support to bdev fio plugin, it seems that some interaction between FIO and QoS causes the application to hang.

## Expected Behavior
It should be possible to add QoS limits on bdev via json_config, even in bdev fio plugin.

## Current Behavior
When a limit is defined on a bdev the fio application hangs.

## Steps to Reproduce
1. Json_config load to fio is added in patch https://review.gerrithub.io/c/spdk/spdk/+/463979/
2. An example test patch converting current configuration file to json for fio tests https://review.gerrithub.io/c/spdk/spdk/+/464647/
3. Remove following lines to reproduce the issue
```
	# For some reason QoS hangs fio at the end of run, if it was enabled by json_rpc
	# Disable it for now and will try to create minimal repro steps
	$rpc_py bdev_set_qos_limit --rw_ios_per_sec 0 Malloc0
	$rpc_py bdev_set_qos_limit --rw_mbytes_per_sec 0 Malloc3
```

## Context (Environment including OS version, SPDK version, etc.)

**Comment by tomzawadzki** [comment]
[Bug scrub] @Comphix Would you like to assist with this issue ?

**Comment by Comphix** [comment]
Will take a look at this one.

**Comment by Comphix** [comment]
@tomzawadzki , could you give more detailed information on the error (or hanging). I've taken a look at the two patches and not found the related log.

Also, it seems the change is to support the JSON conf file which looks like a new configuration and not sure why QoS will affect here as it is used to support the conf file.

If there is some detailed log or way to reproduce this issue, I could try to reproduce it locally.

Thanks, Gang

**Comment by Comphix** [comment]
I've tried to reproduce for below testing steps:

	$rootdir/app/spdk_tgt/spdk_tgt -c ./test/bdev/bdev.conf &
	spdk_tgt=$!
	waitforlisten $spdk_tgt
	# For some reason QoS hangs fio at the end of run, if it was enabled by json_rpc
	# Disable it for now and will try to create minimal repro steps
	$rpc_py bdev_set_qos_limit --rw_ios_per_sec 0 Malloc0
	$rpc_py bdev_set_qos_limit --rw_mbytes_per_sec 0 Malloc3
	$rpc_py save_subsystem_config -n bdev | jq -r '{subsystems: [.] }' > ./test/bdev/bdev.conf.json
	sleep 3
	killprocess $spdk_tgt
	sleep 3

1. Start spdk_tgt:
./app/spdk_tgt/spdk_tgt -c ./test/bdev/bdev.conf &
[1] 5113
root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk# Starting SPDK v20.01-pre git sha1 49757daed / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid5113 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
vbdev_passthru.c: 533:vbdev_passthru_init: *NOTICE*: conf parse matched: Malloc3
vbdev_passthru.c: 629:vbdev_passthru_register: *NOTICE*: Match on Malloc3
vbdev_passthru.c: 672:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x363c5f0
vbdev_passthru.c: 684:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 696:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 709:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 710:vbdev_passthru_register: *NOTICE*: created pt_bdev for: TestPT

2. save configuration where QoS is enabled
./scripts/rpc.py save_subsystem_config -n bdev | jq -r '{subsystems: [.] }' > ./test/bdev/bdev.conf.json
root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk# cat ./test/bdev/bdev.conf.json
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_set_options",
          "params": {
            "bdev_io_pool_size": 65535,
            "bdev_io_cache_size": 256
          }
        },
        {
          "method": "bdev_split_create",
          "params": {
            "base_bdev": "Malloc1",
            "split_count": 2,
            "split_size_mb": 0
          }
        },
        {
          "method": "bdev_split_create",
          "params": {
            "base_bdev": "Malloc2",
            "split_count": 8,
            "split_size_mb": 4
          }
        },
        {
          "method": "bdev_passthru_create",
          "params": {
            "base_bdev_name": "Malloc3",
            "name": "TestPT"
          }
        },
        {
          "method": "bdev_nvme_set_options",
          "params": {
            "action_on_timeout": "none",
            "timeout_us": 0,
            "retry_count": 4,
            "arbitration_burst": 0,
            "low_priority_weight": 0,
            "medium_priority_weight": 0,
            "high_priority_weight": 0,
            "nvme_adminq_poll_period_us": 1000000,
            "nvme_ioq_poll_period_us": 0,
            "io_queue_requests": 0,
            "delay_cmd_submit": true
          }
        },
        {
          "method": "bdev_nvme_set_hotplug",
          "params": {
            "period_us": 100000,
            "enable": false
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc0",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "08c14964-8d61-4343-9245-80ce50d0c4c7"
          }
        },
        {
          "method": "bdev_set_qos_limit",
          "params": {
            "name": "Malloc0",
            "rw_ios_per_sec": 20000  <<<<<<<<<
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc1",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "f13ecf67-9e22-4fe4-b157-fb3e9ebf414a"
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc2",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "937fe9ab-d38b-4827-94f8-0f7feb683990"
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc3",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "2c197e49-cd3e-4419-b219-3bc81b1c7898"
          }
        },
        {
          "method": "bdev_set_qos_limit",
          "params": {
            "name": "Malloc3",
            "rw_mbytes_per_sec": 100  <<<<<<<<<<<
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc4",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "876ff07d-9ae9-4bd9-95bf-1400714a9b25"
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc5",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "319c12b1-be9d-4d14-9844-ab2ef28ba217"
          }
        },
        {
          "method": "bdev_raid_create",
          "params": {
            "name": "raid0",
            "strip_size": 64,
            "raid_level": "raid0",
            "base_bdevs": [
              "Malloc4",
              "Malloc5"
            ]
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc6",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "98b8312a-c1ea-40dd-884a-85ca8bf178fb"
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc7",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "f7f15c71-62bd-4386-a645-96856bb29f5a"
          }
        },
        {
          "method": "bdev_aio_create",
          "params": {
            "name": "AIO0",
            "block_size": 2048,
            "filename": "/tmp/aiofile"
          }
        }
      ]
    }
  ]
}

3. kill spdk_tgt
# ps -ef | grep -i spdk_tgt
root      5113  2062 99 07:34 pts/2    00:03:30 ./app/spdk_tgt/spdk_tgt -c ./test/bdev/bdev.conf
root      5293  5189  0 07:37 pts/3    00:00:00 grep --color=auto -i spdk_tgt
# kill 5113
# ps -ef | grep -i spdk_tgt
root      5312  5189  0 07:37 pts/3    00:00:00 grep --color=auto -i spdk_tg

Looks like the spdk_tgt is killed successfully when QoS is enabled.

**Comment by Comphix** [comment]
@tomzawadzki , please check whether my reproduction steps are same as what you seen. And if there is any detailed log, please add the comment. Thanks, Gang.

**Comment by tomzawadzki** [comment]
@Comphix Thank you for taking on this issue.

Sorry I should have been more clear in steps to reproduce, they assumed one would run test/blockdev.sh with the fio plugin patch applied.
Your steps to produce the failing json_config are correct. The next step would be to use that json_config with fio_plugin. Or run blockdev.sh as that already does this for you.

It is very likely the issue is directly related to fio_plugin threading, as I've been unable to reproduce it on bdevperf for example.

Please see patch https://review.gerrithub.io/c/spdk/spdk/+/481779/ which shows this issue on CI and uses the same json config for bdevperf.

**Comment by Comphix** [comment]
From https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/56797/archive/centos7_autotest/build.log

There is one inconsistent area where

          "params": {
            "name": "Malloc0",
            "rw_ios_per_sec": 20000
          },
          "method": "bdev_set_qos_limit"

          "params": {
            "rw_mbytes_per_sec": 100,
            "name": "Malloc3"
          },
          "method": "bdev_set_qos_limit"

Malloc3 is used as base bdev for TestPT (passthrough bdev) and Malloc0 is used directly for the bdevperf testing. The QoS result of Malloc0 and TestPT is expecting to be 20000 IOPS and 100MB. However from bdevperf, it is pretty low...

Running I/O for 5 seconds...

 Logical core: 0

 Nvme0n1             :    5683.20 IOPS      22.20 MiB/s

 Malloc0             :      51.20 IOPS       0.20 MiB/s

 Malloc1p0           :      51.20 IOPS       0.20 MiB/s

 Malloc1p1           :      51.20 IOPS       0.20 MiB/s

 Malloc2p0           :      51.20 IOPS       0.20 MiB/s

 Malloc2p1           :      51.20 IOPS       0.20 MiB/s

 Malloc2p2           :      51.20 IOPS       0.20 MiB/s

 Malloc2p3           :      51.20 IOPS       0.20 MiB/s

 Malloc2p4           :      51.20 IOPS       0.20 MiB/s

 Malloc2p5           :      51.20 IOPS       0.20 MiB/s

 Malloc2p6           :      51.20 IOPS       0.20 MiB/s

 Malloc2p7           :      51.20 IOPS       0.20 MiB/s

 TestPT              :      51.20 IOPS       0.20 MiB/s

 raid0               :      51.20 IOPS       0.20 MiB/s

 Malloc6             :      51.20 IOPS       0.20 MiB/s

 Malloc7             :      51.20 IOPS       0.20 MiB/s

 AIO0                :    9492.00 IOPS      37.08 MiB/s

I can see the "bdev_gpt_verify" test successfully ended while seems there is some incorrect here.

Will check whether the load config has some problem here together with QoS setting.

**Comment by Comphix** [comment]
I've found out that QoS on Malloc bdev takes no effect as now Malloc bdev sends the ZCOPY io type down. Just raised a patch to enable the ZCOPY in QoS for Malloc at below:

https://review.gerrithub.io/c/spdk/spdk/+/481909

**Comment by tomzawadzki** [comment]
@Comphix Patch looks good to me, but verifying on local machine - did not fix the issue itself.
I've updated the patches to be based on top of yours, to expose the same issue as previously.

**Comment by Comphix** [comment]
Sure. Will also take a further look on the failures you met.

**Comment by Comphix** [comment]
Looks like FIO is hanging from my local reproduction.

Jobs: 16 (f=16): [w(1),V(1),w(1),V(1),w(2),V(2),w(1),V(1),w(1),V(1),w(4)][45.5%][r=1978MiB/s,w=3295MiB/s][r=506k,w=844k IOJobs: 16 (f=16): [w(2),V(1),w(2),V(2),w(5),V(1),w(3)][54.5%][r=1976MiB/s,w=3300MiB/s][r=506k,w=845k IOPS][eta 00m:05s]    Jobs: 16 (f=16): [V(2),w(2),V(1),w(3),V(2),w(1),V(1),w(4)][90.9%][r=1981MiB/s,w=3294MiB/s][r=507k,w=843k IOPS][eta 00m:01sJobs: 16 (f=16): [w(1),V(1),w(2),V(1),w(7),V(1),w(2),V(1)][100.0%][r=1978MiB/s,w=3299MiB/s][r=506k,w=844k IOPS][eta 00m:00Jobs: 1 (f=0): [_(11),f(1),_(4)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
Jobs: 1 (f=0): [_(11),f(1),_(4)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
Jobs: 1 (f=0): [_(11),f(1),_(4)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
Jobs: 1 (f=0): [_(11),f(1),_(4)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]

**Comment by Comphix** [comment]
I've changed back to use the CONF file instead of JSON CONF file, FIO is not hanging when QoS is enabled.

Jobs: 16 (f=16): [V(1),w(1),V(2),w(4),V(1),w(1),V(2),w(1),V(3)][36.4%][r=1973MiB/s,w=3306MiB/s][r=505k,w=846k IOPS][eta 00Jobs: 16 (f=16): [V(3),w(5),V(1),w(3),V(3),w(1)][45.5%][r=1973MiB/s,w=3325MiB/s][r=505k,w=851k IOPS][eta 00m:06s]         Jobs: 16 (f=16): [V(2),w(3),V(1),w(2),V(1),w(1),V(1),w(2),V(2),w(1)][54.5%][r=1967MiB/s,w=3310MiB/s][r=504k,w=847k IOPS][eJobs: 16 (f=16): [w(2),V(2),w(2),V(1),w(1),V(1),w(2),V(2),w(1),V(2)][63.6%][r=1956MiB/s,w=3264MiB/s][r=501k,w=836k IOPS][eJobs: 16 (f=16): [w(1),V(1),w(1),V(1),w(2),V(1),w(4),V(1),w(1),V(1),w(2)][72.7%][r=1967MiB/s,w=3297MiB/s][r=504k,w=844k IOJobs: 16 (f=16): [w(1),V(1),w(6),V(1),w(1),V(1),w(1),V(2),w(1),V(1)][81.8%][r=1975MiB/s,w=3324MiB/s][r=506k,w=851k IOPS][eJobs: 16 (f=16): [w(2),V(2),w(9),V(1),w(1),V(1)][90.9%][r=1983MiB/s,w=3330MiB/s][r=508k,w=853k IOPS][eta 00m:01s]         Jobs: 16 (f=16): [w(1),V(1),f(1),w(2),V(1),w(4),V(4),w(2)][100.0%][r=1954MiB/s,w=3284MiB/s][r=500k,w=841k IOPS][eta 00m:00s]
real    0m11.098s
user    2m38.648s
sys     0m2.590s
 06:07:53       # xtrace_disable
 06:07:53       # '[' no '!=' yes ']'
 06:07:53       # PREV_BASH_OPTS=ehxBE
 06:07:53       # [[ ehxBE == *\x* ]]
 06:07:53       # XTRACE_DISABLED=yes
 06:07:53       # set +x
************************************
END TEST bdev_fio_rw_verify
************************************
 06:07:53       # xtrace_enable
 06:07:53       # rm -f ./local-job_AIO0-15-verify.state ./local-job_Malloc0-0-verify.state ./local-job_Malloc1p0-1-verify.state ./local-job_Malloc1p1-2-verify.state ./local-job_Malloc2p0-3-verify.state ./local-job_Malloc2p1-4-verify.state ./local-job_Malloc2p2-5-verify.state ./local-job_Malloc2p3-6-verify.state ./local-job_Malloc2p4-7-verify.state ./local-job_Malloc2p5-8-verify.state ./local-job_Malloc2p6-9-verify.state ./local-job_Malloc2p7-10-verify.state ./local-job_Malloc6-13-verify.state ./local-job_Malloc7-14-verify.state ./local-job_raid0-12-verify.state ./local-job_TestPT-11-verify.state
 06:07:53       # rm -f /home/gangcao/storage17/20160628/waikiki/spdk/test/bdev/bdev.fio

Not sure what's the different here between CONF and JSON CONF to cause the different IO path behavior.

**Comment by Comphix** [comment]
Another interesting finding:

bdev_fio_trim runs well with JSON conf and enabled QoS.

Looks like the handing at bdev_fio_verify case.

************************************
START TEST bdev_fio_trim
************************************
 07:46:17       # xtrace_enable
 07:46:17       # fio_bdev --ioengine=spdk_bdev --iodepth=8 --bs=4k --runtime=10 /spdk/test/bdev/bdev.fio --spdk_conf=./test/bdev/bdev.conf --output=./blockdev_trim.txt
 07:46:17       # local fio_dir=/home/gangcao/storage17/fio
 07:46:17       # local bdev_plugin=/spdk/examples/bdev/fio_plugin/fio_plugin
 07:46:17       # local asan_lib
  07:46:17      # ldd /spdk/examples/bdev/fio_plugin/fio_plugin
  07:46:17      # grep libasan
  07:46:17      # awk '{print $3}'
 07:46:17       # asan_lib=
 07:46:17       # LD_PRELOAD=' /spdk/examples/bdev/fio_plugin/fio_plugin'
 07:46:17       # /home/gangcao/storage17/fio/fio --ioengine=spdk_bdev --iodepth=8 --bs=4k --runtime=10 /spdk/test/bdev/bdev.fio --spdk_conf=./test/bdev/bdev.conf --output=./blockdev_trim.txt
Starting SPDK v20.01-pre git sha1 ad30eeb4d / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid14931 ]
EAL: No available hugepages reported in hugepages-1048576kB
vbdev_passthru.c: 533:vbdev_passthru_init: *NOTICE*: conf parse matched: Malloc3
vbdev_passthru.c: 629:vbdev_passthru_register: *NOTICE*: Match on Malloc3
vbdev_passthru.c: 672:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x7f0d40dd8730
vbdev_passthru.c: 684:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 696:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 709:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 710:vbdev_passthru_register: *NOTICE*: created pt_bdev for: TestPT
Jobs: 15 (f=13): [W(5),f(2),W(8)][100.0%][r=0KiB/s,w=34.5GiB/s,t=34.5GiB/s][r=0,w=9055k,t=9055k IOPS][eta 00m:00s]
real    0m11.041s
user    2m30.779s
sys     0m0.643s
 07:46:28       # xtrace_disable
 07:46:28       # '[' no '!=' yes ']'
 07:46:28       # PREV_BASH_OPTS=ehxBE
 07:46:28       # [[ ehxBE == *\x* ]]
 07:46:28       # XTRACE_DISABLED=yes
 07:46:28       # set +x
************************************
END TEST bdev_fio_trim
************************************

**Comment by Comphix** [comment]
Have a local run to remove FIO job for TestPT (QoS is on its base Malloc3),  the FIO can run if QoS is enabled and together with JSON conf.

Jobs: 14 (f=14): [W(14)][100.0%][r=0KiB/s,w=33.7GiB/s,t=33.7GiB/s][r=0,w=8822k,t=8822k IOPS][eta 00m:00s]
job_Malloc0: (groupid=0, jobs=14): err= 0: pid=4186: Sat Jan 18 11:36:52 2020
  write: IOPS=8774k, BW=33.5GiB/s (35.9GB/s)(335GiB/10001msec)
    slat (nsec): min=119, max=77555, avg=290.73, stdev=186.27
    clat (nsec): min=84, max=981314, avg=240.82, stdev=10309.88
     lat (nsec): min=303, max=981445, avg=531.55, stdev=10309.90
    clat percentiles (nsec):
     | 50.000th=[   129], 99.000th=[   219], 99.900th=[   342],
     | 99.990th=[962560], 99.999th=[970752]
   bw (  MiB/s): min=   77, max= 2939, per=7.20%, avg=2467.16, stdev=718.46, samples=280
   iops        : min=19960, max=752494, avg=631592.87, stdev=183925.35, samples=280
   trim: IOPS=8774k, BW=33.5GiB/s (35.9GB/s)(335GiB/10001msec)
    slat (nsec): min=301, max=37724, avg=509.49, stdev=312.17
    clat (nsec): min=86, max=39343, avg=138.28, stdev=124.70
     lat (nsec): min=437, max=56524, avg=647.77, stdev=333.94
    clat percentiles (nsec):
     | 50.000th=[  139], 99.000th=[  161], 99.900th=[  274], 99.990th=[ 3824],
     | 99.999th=[16064]
   bw (  MiB/s): min=   77, max= 2939, per=7.20%, avg=2467.16, stdev=718.46, samples=280
   iops        : min=19960, max=752494, avg=631592.88, stdev=183925.36, samples=280
  lat (nsec)   : 100=0.02%, 250=99.80%, 500=0.15%, 750=0.01%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  lat (usec)   : 1000=0.01%
  cpu          : usr=99.73%, sys=0.00%, ctx=86, majf=0, minf=45
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,87750694,87750700, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=33.5GiB/s (35.9GB/s), 33.5GiB/s-33.5GiB/s (35.9GB/s-35.9GB/s), io=335GiB (359GB), run=10001-10001msec
   TRIM: bw=33.5GiB/s (35.9GB/s), 33.5GiB/s-33.5GiB/s (35.9GB/s-35.9GB/s), io=335GiB (359GB), run=10001-10001msec

root@storage35:/home/gangcao/storage17/spdk/examples/bdev/fio_plugin# cat qos.fio
[global]
ioengine=./fio_plugin
spdk_json_conf=./bdev.conf.json
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=10
iodepth=1
rw=randrw
bs=4k
norandommap=1
percentile_list=50:99:99.9:99.99:99.999
rw=trimwrite

[job_Malloc0]
filename=Malloc0
[job_Malloc1p0]
filename=Malloc1p0
[job_Malloc1p1]
filename=Malloc1p1
[job_Malloc2p0]
filename=Malloc2p0
[job_Malloc2p1]
filename=Malloc2p1
[job_Malloc2p2]
filename=Malloc2p2
[job_Malloc2p3]
filename=Malloc2p3
[job_Malloc2p4]
filename=Malloc2p4
[job_Malloc2p5]
filename=Malloc2p5
[job_Malloc2p6]
filename=Malloc2p6
[job_Malloc2p7]
filename=Malloc2p7
#[job_TestPT]
#filename=TestPT
[job_raid0]
filename=raid0
[job_Malloc6]
filename=Malloc6
[job_Malloc7]
filename=Malloc7

**Comment by Comphix** [comment]
Looks like this is relating to the sequence of when Passthrough device is created.

With below change (1. create base Bdev; 2. enable QoS; 3. create Passthrough bdev), it looks like no problem. This is same logic for the CONF file where QoS is enabled at the time of Bdev creation (that's why CONF file works).

I've changed the content of JSON file to move the creation of Passthrough device after the QoS setting, now it passes:

vim bdev.conf.json
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_set_options",
          "params": {
            "bdev_io_pool_size": 65535,
            "bdev_io_cache_size": 256
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc3",
            "num_blocks": 65536,
            "block_size": 512,
            "uuid": "3d6541d0-a196-4453-babb-ea154a17551b"
          }
        },
        {
          "method": "bdev_set_qos_limit",
          "params": {
            "name": "Malloc3",
            "rw_mbytes_per_sec": 100
          }
        },
        {
          "method": "bdev_passthru_create",
          "params": {
            "base_bdev_name": "Malloc3",
            "name": "TestPT"
          }
        }
      ]
    }
  ]
}
~
~
~
~
~
~
~
~
~
"bdev.conf.json" 39L, 848C written
root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk/examples/bdev/fio_plugin# fio qos.fio
job_TestPT: (g=0): rw=trimwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=1
fio-3.3-dirty
Starting 1 thread
Starting SPDK v20.01-pre git sha1 ad30eeb4d / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4538 ]
EAL: No available hugepages reported in hugepages-1048576kB
vbdev_passthru.c: 629:vbdev_passthru_register: *NOTICE*: Match on Malloc3
vbdev_passthru.c: 672:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x7f6574d30ea0
vbdev_passthru.c: 684:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 696:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 709:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 710:vbdev_passthru_register: *NOTICE*: created pt_bdev for: TestPT
11 max_units 1
Jobs: 1 (f=1): [W(1)][100.0%][r=0KiB/s,w=1820KiB/s,t=1824KiB/s][r=0,w=455,t=456 IOPS][eta 00m:00s]
job_TestPT: (groupid=0, jobs=1): err= 0: pid=4587: Sat Jan 18 11:47:44 2020
  write: IOPS=454, BW=1820KiB/s (1863kB/s)(17.8MiB/10001msec)
    slat (nsec): min=427, max=15417, avg=536.07, stdev=375.85
    clat (usec): min=1056, max=1138, avg=1098.80, stdev= 4.82
     lat (usec): min=1057, max=1138, avg=1099.34, stdev= 4.81
    clat percentiles (usec):
     | 50.000th=[ 1106], 99.000th=[ 1106], 99.900th=[ 1123], 99.990th=[ 1139],
     | 99.999th=[ 1139]
   bw (  KiB/s): min= 1812, max= 1832, per=100.00%, avg=1818.95, stdev= 5.47, samples=19
   iops        : min=  453, max=  458, avg=454.74, stdev= 1.37, samples=19
   trim: IOPS=454, BW=1820KiB/s (1863kB/s)(17.8MiB/10001msec)
    slat (nsec): min=373, max=14928, avg=423.63, stdev=306.61
    clat (usec): min=666, max=1136, avg=1097.67, stdev= 8.18
     lat (usec): min=669, max=1137, avg=1098.10, stdev= 8.15
    clat percentiles (usec):
     | 50.000th=[ 1106], 99.000th=[ 1106], 99.900th=[ 1123], 99.990th=[ 1139],
     | 99.999th=[ 1139]
   bw (  KiB/s): min= 1812, max= 1824, per=100.00%, avg=1819.37, stdev= 4.86, samples=19
   iops        : min=  453, max=  456, avg=454.84, stdev= 1.21, samples=19
  lat (usec)   : 750=0.01%
  lat (msec)   : 2=99.99%
  cpu          : usr=99.84%, sys=0.00%, ctx=5, majf=0, minf=5
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,4550,4550, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=1820KiB/s (1863kB/s), 1820KiB/s-1820KiB/s (1863kB/s-1863kB/s), io=17.8MiB (18.6MB), run=10001-10001msec
   TRIM: bw=1820KiB/s (1863kB/s), 1820KiB/s-1820KiB/s (1863kB/s-1863kB/s), io=17.8MiB (18.6MB), run=10001-10001msec
root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk/examples/bdev/fio_plugin#

**Comment by Comphix** [comment]
So that the proper fix is that when generating the content of JSON configure, it shall move the operations of Base bdev to the earlier part (like here creation of base bdev and enabling QoS on base bdev), then append the operation on the virtual base which is based on the Base bdev (like here the creation of passthrough bdev).

**Comment by Comphix** [comment]
Or the other fix is when replaying the JSON RPC, needs to handle the operations on the base bdev first (like after the creation of the base bdev, then enable the QoS on it before the virtual bdev creation).

**Comment by Comphix** [comment]
Or maybe the other fix is that once QoS is enabled on base bdev, it is not allowed to be consumed by another Virtual bdev as in this case the consumed base bdev is hide behind the Virtual bdev and the QoS could be enabled on the Virtual bdev instead. This seems like a more reasonable fix to restrict the QoS always enabled on the Virtual Bdev or on the normal Bdev when both of these two types exposed to the upper layer.

Is this the proper fix?

**Comment by Comphix** [comment]
@tomzawadzki , to not block your change, you could just change below one line to enable QoS on the Non base base.

diff --git a/test/bdev/bdev.conf.in b/test/bdev/bdev.conf.in
index b80b4fefd..750ae4df2 100644
--- a/test/bdev/bdev.conf.in
+++ b/test/bdev/bdev.conf.in
@@ -33,7 +33,7 @@
   # multiple of 10
   # Assign 100 (MB) bandwidth for the Malloc3 block
   # device
-  Limit_BPS Malloc3 100
+  Limit_BPS Malloc6 100

 [RAID0]
   Name raid0

I've verified on my local environment, it could pass successfully.

Jobs: 15 (f=6): [f(2),W(1),f(1),W(1),f(1),W(1),f(3),W(2),f(1),W(1),f(1)][100.0%][r=0KiB/s,w=33.5GiB/s,t=33.5GiB/s][r=0,w=8788k,t=8788k IOPS][eta 00m:00s]
real    0m30.935s
user    7m30.128s
sys     0m0.505s
 13:55:55       # xtrace_disable
 13:55:55       # '[' no '!=' yes ']'
 13:55:55       # PREV_BASH_OPTS=ehxBE
 13:55:55       # [[ ehxBE == *\x* ]]
 13:55:55       # XTRACE_DISABLED=yes
 13:55:55       # set +x
************************************
END TEST bdev_fio_trim
************************************

Many thanks for raising this issue. Gang

**Comment by Comphix** [comment]
Not sure whether this issue is relating to FIO thread scheduling. Seems it is hanging at below FIO logic to determine the jobs are finished...

0x00007f87683441ad in nanosleep () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f87683441ad in nanosleep () from /lib64/libc.so.6
#1  0x00007f8768374ec4 in usleep () from /lib64/libc.so.6
#2  0x000000000046677e in do_usleep (usecs=10000) at backend.c:2136
#3  run_threads (sk_out=sk_out@entry=0x0) at backend.c:2451
#4  0x0000000000466e2d in fio_backend (sk_out=sk_out@entry=0x0) at backend.c:2500
#5  0x000000000040ecdc in main (argc=2, argv=0x7ffe6991f1e8, envp=<optimized out>) at fio.c:65

**Comment by Comphix** [comment]
Digging into why the FIO is hanging, it is found that there is timer-poller on the thread and later found out that it seems that the PassThrough vbdev does not close the base bdev. Need to take a further check for a proper fix.

**Comment by Comphix** [comment]
With same configuration, bdevperf runs well together with JSON config and enabled QoS.

Seems like still relating to the FIO threading which behaves differently here. Need to dig more.

**Comment by Comphix** [comment]
Raise the patch at https://review.gerrithub.io/c/spdk/spdk/+/483547 and verify it works both for the JSON conf and conf file.

**Comment by Comphix** [comment]
With more debugging information, the issue is not clear.

We spawn a "dummy" thread for the initialization of the bdev layer for the FIO operation and each FIO job has its own thread.

(1) Case for the CONF file, the QoS is enabled at the time of bdev creation on the same thread (here it is the dummy thread).

(2) Case for JSON file, the QoS is set through RPC and enabled only when the bdev's channel is created. And the channel creation is in the FIO job's own thread which is different from the dummy init thread. Details below:

{code}
gdb) bt
#0  bdev_enable_qos (bdev=0x7fffd0d06a40, ch=0x7fffcc0020a0) at bdev.c:2261
#1  0x00007fffe6fa4cd6 in bdev_channel_create (io_device=0x7fffd0d06a41, ctx_buf=0x7fffcc0020a0)
    at bdev.c:2524
#2  0x00007fffe6f97c5b in spdk_get_io_channel (io_device=0x7fffd0d06a41) at thread.c:1175
#3  0x00007fffe6fa57b0 in spdk_bdev_get_io_channel (desc=0x7fffd0d2f910) at bdev.c:2779
#4  0x00007fffe6f0f58d in pt_bdev_ch_create_cb (io_device=0x7fffd0d2f720, ctx_buf=0x7fffcc001fc0)
    at vbdev_passthru.c:438
#5  0x00007fffe6f97c5b in spdk_get_io_channel (io_device=0x7fffd0d2f720) at thread.c:1175
#6  0x00007fffe6f0f3e5 in vbdev_passthru_get_io_channel (ctx=0x7fffd0d2f720) at vbdev_passthru.c:388
#7  0x00007fffe6fa49bd in bdev_channel_create (io_device=0x7fffd0d2f731, ctx_buf=0x7fffcc001ec0)
    at bdev.c:2450
#8  0x00007fffe6f97c5b in spdk_get_io_channel (io_device=0x7fffd0d2f731) at thread.c:1175
#9  0x00007fffe6fa57b0 in spdk_bdev_get_io_channel (desc=0x7fffcc001dd0) at bdev.c:2779
#10 0x00007fffe6efc2ef in spdk_fio_bdev_open (arg=0x7fffd6cff000) at fio_plugin.c:481
#11 0x00007fffe6f95e48 in _spdk_msg_queue_run_batch (thread=0x7fffcc001a30, max_msgs=8) at thread.c:433
#12 0x00007fffe6f96112 in spdk_thread_poll (thread=0x7fffcc001a30, max_msgs=0, now=25797896001010548)
    at thread.c:506
#13 0x00007fffe6efc9ac in spdk_fio_poll_thread (fio_thread=0x7fffcc0019f0) at fio_plugin.c:671
#14 0x00007fffe6efc464 in spdk_fio_init (td=0x7fffd6cff000) at fio_plugin.c:512
#15 0x000000000041df0d in td_io_init (td=td@entry=0x7fffd6cff000) at ioengines.c:403
#16 0x0000000000464fa1 in thread_main (data=<optimized out>) at backend.c:1726
#17 0x00007ffff684ce25 in start_thread () from /lib64/libpthread.so.0
#18 0x00007ffff637634d in clone () from /lib64/libc.so.6
{code}

3. Continue with the JSON file, in this case, there is a QoS Poller created on the FIO job thread so that when the FIO run ends, it calls to cleanup the Job information and consider there is a timer Poller there, it continues to wait this Poller to remove (that's why it hangs)

4. For the CONF file case, as the QoS poller is on the dummy init thread, all FIO threads has no job and could cleanup clearly.

In this case, as the dummy init thread does not Get_IO_Channel of the device while only opening the device, there is no possible to have the QoS poller to run on the init thread.

In this case, this is more like a test configuration or FIO plugin usage issue (I've tried to change the FIO plugin logic while it is causing side effects).

**Comment by changpe1** [comment]
@Comphix After reading your analysis, for the JSON case, the QoS poller is registered in the FIO thread, the spdk_thread_is_idle(fio_thread->thread)) is not idle, do you know which list in this thread is not null, the active list or the timer list ?
I'm wondering why spdk_fio_poll_thread() didn't work for this case.

**Comment by shuhei-matsumoto** [comment]
Hi @tomzawadzki 

Will you move the patch to load json config to fio to review.spdk.io?
It will be helpful for others to reproduce or investigate the issue.

Thanks,
Shuhei

**Comment by shuhei-matsumoto** [comment]
@tomzawadzki Sorry, link is still valid and I knew the current status. Please ignore my question.

**Comment by Comphix** [comment]
The QoS poller is created at the time of RPC call which is the dummy FIO init thread. However the QoS poller related channel and thread is from the device which is opened on the FIO job thread. The logic of FIO init thread and FIO job thread is just one kind of implementation in SPDK FIO plugin which means the QoS logic is correct here.

Problem here is that when the FIO ends, the FIO job thread starts to cleanup and checks whether it is idle. In the JSON/RPC case, the QoS poller is registered there so that it can not move forward as the thread is not idle.

For the CONF case, it is different, the QoS is enabled when parsing the CONF file which is handled by the FIO init thread so that the FIO job thread can cleanup successfully.

@changpe1 @shuhei-matsumoto , for the FIO JSON patch, actually I have enabled in my patch series https://review.spdk.io/gerrit/c/spdk/spdk/+/665/3 and it could successfully complete.

**Comment by Comphix** [comment]
The problem is the QoS poller can not be unregistered from the FIO job thread is using JSON/RPC way. So that my change here is to slight adjust the FIO logic to kick off the bdev destruction first to remove the QoS poller first. One problem blocking here is that when closing the bdev desc, it is opened on the base bdev and get initialized by the bdev layer through the FIO init thread while as its virtual device is opened at the FIO job thread (treated as the FIO target), so that it hitting the assert when closing the bdev (desc->thread != spdk_get_thread()). That's my purpose to change the spdk_bdev_close().

**Comment by changpe1** [comment]
> The QoS poller is created at the time of RPC call which is the dummy FIO init thread. However the QoS poller related channel and thread is from the device which is opened on the FIO job thread. The logic of FIO init thread and FIO job thread is just one kind of implementation in SPDK FIO plugin which means the QoS logic is correct here.
> 
> Problem here is that when the FIO ends, the FIO job thread starts to cleanup and checks whether it is idle. In the JSON/RPC case, the QoS poller is registered there so that it can not move forward as the thread is not idle.
> 
> For the CONF case, it is different, the QoS is enabled when parsing the CONF file which is handled by the FIO init thread so that the FIO job thread can cleanup successfully.
> 
> @changpe1 @shuhei-matsumoto , for the FIO JSON patch, actually I have enabled in my patch series https://review.spdk.io/gerrit/c/spdk/spdk/+/665/3 and it could successfully complete.

Thanks, what if we just removed the  spdk_thread_is_idle(fio_thread->thread)) in your patch, does that work?

**Comment by shuhei-matsumoto** [comment]
Hi @changpe1 @Comphix 

spdk_thread_exit will fail if there is any poller even if it is ok now. My patch series will prohibit it.

If we change the close caller, can we change the open caller? Or sending SPDK message?
SPDK thread and FIO thread is separated, so we can do any what we want.

I’ll try to catch up

**Comment by jimharris** [comment]
Hi @Comphix,

I would prefer to not change spdk_bdev_close() behavior to 'fix' this case.  It is better to enforce caller to always close the descriptor on the same thread it was opened.  It avoids misuse of bdev descriptors, including trying to close the same descriptor on multiple threads at once.

It would be better to change this by modifying the fio plugin instead.  Is there a way to only change the use of spdk threads in the plugin to fix this?

-Jim

**Comment by Comphix** [comment]
Will take a further look.

**Comment by Comphix** [comment]
Patch has been updated with a new solution.

**Comment by optimistyzy** [comment]
@Comphix Is there any update on this issue? Or this issue is solved? // I remember that we have a disucssions in one bug scrum meeting.

**Comment by Comphix** [comment]
JSON related changes for FIO as a configurable parameter has been merged already. For together with QoS itself, I will take a look and verify that later.

**Comment by Comphix** [comment]
Verified the latest code, it seems like this issue is still existing. Need to further debug.

**Comment by Comphix** [comment]
Looks like still need to apply the fio changes in https://review.spdk.io/gerrit/c/spdk/spdk/+/662

For changes in bdev, it looks like not able to solve the issues from fio side. 

We rely on some callbacks from the virtual bdev close to trigger the base bdev close. In this case, the base bdev is enabled QoS and there is the active QoS poller on the thread. This poller will be removed if its related bdev is closed. However in the fio case, as fio's job thread is waiting there is no poller before calling the bdev close operation. So in this case, this seems to be a deadlock.

My previous change is to spawn a new fio cleanup thread and not block other operations so that the overall cleanup could move forward.

**Comment by tomzawadzki** [comment]
Patch resolving this issue was merged https://review.spdk.io/gerrit/c/spdk/spdk/+/3682
@Comphix confirmed in comment there that this fixes this issue.

Added patch that removes FIXME for this test case https://review.spdk.io/gerrit/c/spdk/spdk/+/3726

**Comment by Comphix** [comment]
Patch has been merged. Close this issue.
