### ISSUE TITLE
Probe fails every other time

### ISSUE THREAD

**Issue by yrashk** [spdk/spdk#139]
First of all, thanks for this great library!

I ran into an odd case where spdk_nvme_probe() would fail every other time (see the log below). The NVMe SSD is INTEL SSDPE2MX450G7. I am running it on 17.03

What is the best way to figure out the source of this problem?

```shell
$ sudo ./spdk/examples/nvme/hello_world/hello_world
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 1 --file-prefix=spdk_pid30598 ]
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a53 spdk_nvme
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a53 spdk_nvme
Attaching to 0000:03:00.0
Attached to 0000:03:00.0
Using controller INTEL SSDPE2MX450G7  (CVPF641600J1450RGN  ) with 1 namespaces.
  Namespace ID: 1 size: 450GB
Initialization complete.
Hello world!

$ sudo ./spdk/examples/nvme/hello_world/hello_world
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 1 --file-prefix=spdk_pid30601 ]
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a53 spdk_nvme
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a53 spdk_nvme
Attaching to 0000:03:00.0
nvme_ctrlr.c:1237:nvme_ctrlr_process_init: ***ERROR*** Initialization timed out in state 3
spdk_nvme_probe() failed

$ sudo ./spdk/examples/nvme/hello_world/hello_world
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 1 --file-prefix=spdk_pid30633 ]
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a53 spdk_nvme
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a53 spdk_nvme
Attaching to 0000:03:00.0
Attached to 0000:03:00.0
Using controller INTEL SSDPE2MX450G7  (CVPF641600J1450RGN  ) with 1 namespaces.
  Namespace ID: 1 size: 450GB
Initialization complete.
Hello world!
```

On master, the behaviour is the same, but the error is slightly different (different state):

```
nvme_ctrlr.c:1248:nvme_ctrlr_process_init: ***ERROR*** Initialization timed out in state 4
spdk_nvme_probe() failed
```

**Comment by jimharris** [comment]
> On Apr 16, 2017, at 12:25 AM, Yurii Rashkovskii <notifications@github.com> wrote:
> 
> First of all, thanks for this great library!
> 
> I ran into an odd case where spdk_nvme_probe() would fail every other time (see the log below). The NVMe SSD is INTEL SSDPE2MX450G7.
> 
> What is the best way to figure out the source of this problem?

Hi Yuri,

Could you please check if you have commit 36a793ad6 (nvme: Add a quirk to delay before enabling) in your tree?  This patch was committed about two weeks ago, and should resolve the issue you are seeing.

Thanks,

-Jim

**Comment by yrashk** [comment]
Hi Jim, 

Thank you very much for the advice. I just retried this off the top of master and I like I pointed out in the original issue, I am still experiencing this problem (exactly every other probing fails) except that the error is not "Initialization timed out in state 4" instead of "Initialization timed out in state 3".

Is there anything else I can investigate to find the source of this issue? I'd be happy to provide any assistance with this issue, including remote access to the machine with the SSD in question, if necessary.

What else can I check to see where this behaviour is stemming from?

**Comment by yrashk** [comment]
I believe I discovered the source of the issue. My device vendor_id:device_id is 8086:0a53, however NVME_QUIRK_DELAY_BEFORE_ENABLE is only defined for 8086:0953. Once I added NVME_QUIRK_DELAY_BEFORE_ENABLE to 0x0A53, the problem went away.

Do you want me to submit a PR for this or how should we handle this?

**Comment by jimharris** [comment]
> On Apr 17, 2017, at 8:21 AM, Yurii Rashkovskii <notifications@github.com> wrote:
> 
> I believe I discovered the source of the issue. My device vendor_id:device_id is 8086:0a53, however NVME_QUIRK_DELAY_BEFORE_ENABLE is only defined for 8086:0953. Once I added NVME_QUIRK_DELAY_BEFORE_ENABLE to 0x0A53, the problem went away.
> 
> Do you want me to submit a PR for this or how should we handle this?

Hi Yuri,

Thank you for your report.

No need to submit a PR.  We have identified other SSDs that also require this DELAY_BEFORE_ENABLE quirk, and will be pushing out a patch later today that enables this behavior by default since it is only a 100us delay.

-Jim

**Comment by yrashk** [comment]
Sounds fantastic!

**Comment by benlwalker** [comment]
Hi Yuri,

Have you tried updating the SSD to the latest firmware? The device ID may change to 0x0953 on update. At least, that's my understanding of what should happen.

The quirk that fixes the issue is not particularly onerous and it has become increasingly required, so we're considering changing it from a quirk to baseline behavior.

**Comment by yrashk** [comment]
Hi Ben,

I haven't tried updating the firmware, because this SSD is not my hardware (it's a rented dedicated server I am testing things on).

I really hope this can become baseline behaviour! My understanding was that @jimharris said it will land as such today.

**Comment by benlwalker** [comment]
The patch to make this the baseline behavior has been merged to master. Please let us know if it fixes the issue.

**Comment by yrashk** [comment]
It did indeed fix the issue! Thanks!

**Comment by tone-zhang** [comment]
Observed the "time out" error when debug SPDK in Ceph. The SPDK version is f60effdd75b782542a539eaad00d8f8f1d2df988.

After change the delay in "https://github.com/spdk/spdk/blob/f60effdd75b782542a539eaad00d8f8f1d2df988/lib/nvme/nvme_ctrlr.c#L1619" from "spdk_delay_us(100);" to "spdk_delay_us(100000);".

The NVMe device is "Intel Corporation SSD 750 Series [Add-in Card]".

Thanks!

**Comment by darsto** [comment]
This should be fixed on master. We've increased the sleep time after each
PCI reset from 500ms to 2s. See the following patches:

https://github.com/spdk/spdk/commit/951bb3a458748ae419f6507c805f639295b296fa
https://github.com/spdk/spdk/commit/0258728f2baa795e438229565eb7e103ad56dceb

Can you try to reproduce this timeout with the above two?
D.

**Comment by tone-zhang** [comment]
@darsto Thanks a lot for your response.

Regarding the issue has been closed here, I have created new one to track the "time out" issue. Could you please move to https://github.com/spdk/spdk/issues/482.

Sorry for the inconvenience. Thanks!
