### ISSUE TITLE
[qemu] spdk_tgt receives SIGILL while attempting to attach to a nvme controller

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1458]
```
SPDK: v20.04-rc1-552-ga1c00096d
QEMU: 4.2.0 (VM: Fedora30, kernel 5.6.13)
```

Config:
```
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "name": "Nvme0",
            "trtype": "pcie",
            "traddr": "0000:00:03.0"
          },
          "method": "bdev_nvme_attach_controller"
        },
        {
          "params": {
            "name": "Nvme1",
            "trtype": "pcie",
            "traddr": "0000:00:04.0"
          },
          "method": "bdev_nvme_attach_controller"
        }
      ]
    }
  ]
}
```
Qemu's cmdline:
```
root@debianMB[SPDK]:/spdk_project/alt/jenkins_build_pool/packer# grep qemu-s /proc/*/comm
/proc/3107674/comm:qemu-system-x86
root@debianMB[SPDK]:/spdk_project/alt/jenkins_build_pool/packer# mapfile -d $'\0' -t c </proc/3107674/cmdline
root@debianMB[SPDK]:/spdk_project/alt/jenkins_build_pool/packer# printf '%s\n' "${c[@]}"
/extra/qemu/qemu-4.2.0/build/x86_64-softmmu/qemu-system-x86_64
-drive
file=/tmp/qemu/nvme0.img,if=none,id=D0,format=raw
-device
nvme,logical_block_size=4096,physical_block_size=4096,drive=D0,serial=kaka-29715,cmb_size_mb=128
-drive
file=/tmp/qemu/nvme1.img,if=none,id=D1,format=raw
-device
nvme,logical_block_size=4096,physical_block_size=4096,drive=D1,serial=kaka-14582,cmb_size_mb=256
-drive
file=/tmp/qemu/nvme2.img,if=none,id=D2,format=raw
-device
nvme,logical_block_size=4096,physical_block_size=4096,drive=D2,serial=kaka-22321,cmb_size_mb=512
-drive
file=/tmp/qemu/nvme3.img,if=none,id=D3,format=raw
-device
nvme,logical_block_size=4096,physical_block_size=4096,drive=D3,serial=kaka-14267,cmb_size_mb=128
-cpu
host
-machine
q35,accel=kvm
-smp
8
-m
12G
-enable-kvm
-serial
stdio
-nic
tap,id=hostnet0,model=virtio-net-pci,mac=ee:ff:dd:00:00:00
-drive
if=virtio,file=/var/spdk/packer/build/fedora-30/fedora30,cache=writeback
root@debianMB[SPDK]:/spdk_project/alt/jenkins_build_pool/packer#
```

Whenever any app (`spdk_tgt` is just an example) is run with the above config, it's being immediately killed with `SIGILL`:
```
[root@fedora30-cloud-20166 spdk]# ./build/bin/spdk_tgt --json j
Starting SPDK v20.07-pre git sha1 4e5c87587 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid2297 ]
EAL: No available hugepages reported in hugepages-1048576kB
[2020-06-25 09:25:31.934620] app.c: 644:spdk_app_start: *NOTICE*: Total cores available: 1
[2020-06-25 09:25:32.221397] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
[2020-06-25 09:25:32.222247] accel_engine.c: 229:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Illegal instruction (core dumped)
[root@fedora30-cloud-20166 spdk]#
```

Short bt:
```
 0x00000000004524f9 in nvme_pcie_qpair_submit_tracker (qpair=qpair@entry=0x200023a17c98, tr=<optimized out>) at nvme_pcie.c:1339
#1  0x0000000000453f30 in nvme_pcie_qpair_submit_request (qpair=0x200023a17c98, req=<optimized out>) at nvme_pcie.c:2284
#2  0x0000000000454a47 in _nvme_qpair_submit_request (req=0x200023a17a80, qpair=0x200023a17c98) at nvme_qpair.c:710
#3  nvme_qpair_submit_request (qpair=0x200023a17c98, req=0x200023a17a80) at nvme_qpair.c:766
#4  0x0000000000448aec in nvme_ctrlr_submit_admin_request (ctrlr=ctrlr@entry=0x200023a17e40, req=<optimized out>) at nvme_ctrlr.c:2876
#5  0x000000000044567d in nvme_ctrlr_cmd_identify (ctrlr=ctrlr@entry=0x200023a17e40, cns=cns@entry=1 '\001', cntid=cntid@entry=0, nsid=nsid@entry=0, payload=payload@entry=0x200023a18430,
    payload_size=payload_size@entry=4096, cb_fn=0x446e50 <nvme_ctrlr_identify_done>, cb_arg=0x200023a17e40) at nvme_ctrlr_cmd.c:157
#6  0x0000000000449e57 in nvme_ctrlr_identify (ctrlr=0x200023a17e40) at nvme_ctrlr.c:1379
#7  nvme_ctrlr_process_init (ctrlr=ctrlr@entry=0x200023a17e40) at nvme_ctrlr.c:2630
#8  0x00000000004583f9 in nvme_ctrlr_poll_internal (probe_ctx=0x183a8a0, ctrlr=0x200023a17e40) at nvme.c:1372
#9  spdk_nvme_probe_poll_async (probe_ctx=0x183a8a0) at nvme.c:1372
#10 0x000000000041bc8c in bdev_nvme_async_poll (arg=0x183a3c0) at bdev_nvme.c:1737
#11 0x000000000049dfb9 in thread_poll (now=7113578716987, max_msgs=0, thread=0x17fb340) at thread.c:646
#12 spdk_thread_poll (thread=thread@entry=0x17fb340, max_msgs=max_msgs@entry=0, now=7113578716987) at thread.c:689
#13 0x0000000000486659 in _reactor_run (reactor=0x17fb000) at reactor.c:326
#14 reactor_run (arg=0x17fb000) at reactor.c:382
#15 0x0000000000486b81 in spdk_reactors_start () at reactor.c:477
#16 0x0000000000484f29 in spdk_app_start (opts=opts@entry=0x7fff55abcbb0, start_fn=start_fn@entry=0x416b10 <spdk_tgt_started>, arg1=arg1@entry=0x0) at app.c:691
#17 0x00000000004133b8 in main (argc=3, argv=0x7fff55abcd68) at spdk_tgt.c:120
```

[spdk_dd_tgt.tar.zip](https://github.com/spdk/spdk/files/4830416/spdk_dd_tgt.tar.zip) - core dump (sorry for the extra. zip, apparently github can't handle a plain .tar archive).

**Comment by jimharris** [comment]
Was spdk_tgt built on the host or inside the VM?

**Comment by mikeBashStuff** [comment]
@jimharris Inside the VM.

**Comment by jimharris** [comment]
Do we always use machine=q35 in our tests?

My guess is that we're getting the SIGILL on the SSE2 commands in nvme_pcie_copy_command.  If you're building it inside the VM, it *should* use a normal copy by assignment and not the SSE2 commands. Could you try modifying that function temporarily to remove use of SSE2 in that function and retest?  That will make sure we're going down the right path here with the debug.

**Comment by mikeBashStuff** [comment]
@jimharris This is just my local setup I brought up for  the spdk_dd stuff. Will try to go with you suggestion to see if it helps. thanks!

**Comment by mikeBashStuff** [comment]
@jimharris With this change (not quite sure if this was the right way to do it), I got the same result (bt looks exactly the same):
```
diff --git a/lib/nvme/nvme_pcie.c b/lib/nvme/nvme_pcie.c
index ec9058cbd..1904305aa 100644
--- a/lib/nvme/nvme_pcie.c
+++ b/lib/nvme/nvme_pcie.c
@@ -1157,17 +1157,7 @@ static inline void
 nvme_pcie_copy_command(struct spdk_nvme_cmd *dst, const struct spdk_nvme_cmd *src)
 {
        /* dst and src are known to be non-overlapping and 64-byte aligned. */
-#if defined(__SSE2__)
-       __m128i *d128 = (__m128i *)dst;
-       const __m128i *s128 = (const __m128i *)src;
-
-       _mm_stream_si128(&d128[0], _mm_load_si128(&s128[0]));
-       _mm_stream_si128(&d128[1], _mm_load_si128(&s128[1]));
-       _mm_stream_si128(&d128[2], _mm_load_si128(&s128[2]));
-       _mm_stream_si128(&d128[3], _mm_load_si128(&s128[3]));
-#else
        *dst = *src;
-#endif
 }
```

I tried with different `-machine` and `-cpu` options but with no luck.

**Comment by jimharris** [comment]
Your changes are correct.  If it's not too much trouble, could you capture a core dump for this modified version as well?

**Comment by jimharris** [comment]
Or even better can you just run your app from gdb, and when it crashes type "disass".  That will disassemble the current function.  Scroll through a bit and you'll see an arrow in the far left column pointing to the current PC.  Either that instruction or the one just before it will be the one that is crashing.

**Comment by mikeBashStuff** [comment]
@jimharris 

Here's the core: [sigill_core.tar.zip](https://github.com/spdk/spdk/files/4846530/sigill_core.tar.zip)

Here's the snippet from the disassemble: 
```
0x0000000000452525 <+245>:   vmovdqu (%rsi),%xmm4
=> 0x0000000000452529 <+249>:   vmovups %xmm4,(%rax)
0x000000000045252d <+253>:   vmovdqu 0x10(%rsi),%xmm5
```

And here's the full output:

```
[root@fedora30-cloud-20264 spdk]# gdb -ex=run --args ./build/bin/spdk_tgt --json k
GNU gdb (GDB) Fedora 8.3-7.fc30
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/bin/spdk_tgt...
Starting program: /git_repos/spdk_repo/spdk/build/bin/spdk_tgt --json k
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Starting SPDK v20.07-pre git sha1 59a91950e / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1200 ]
[New Thread 0x7ffff7aa4700 (LWP 1204)]
EAL: No available hugepages reported in hugepages-1048576kB
[2020-06-29 15:39:08.444226] app.c: 647:spdk_app_start: *NOTICE*: Total cores available: 1
[2020-06-29 15:39:08.789124] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
[2020-06-29 15:39:08.795380] accel_engine.c: 245:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.

Thread 1 "reactor_0" received signal SIGILL, Illegal instruction.
0x0000000000452529 in nvme_pcie_qpair_submit_tracker (qpair=qpair@entry=0x200023a17c98, tr=<optimized out>) at nvme_pcie.c:1329
1329                    pqpair->cmd[pqpair->sq_tail] = req->cmd;
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-9.fc30.x86_64 libaio-0.3.111-4.fc30.x86_64 libuuid-2.33.2-2.fc30.x86_64 numactl-libs-2.0.12-2.fc30.x86_64 openssl-libs-1.1.1g-1.fc30.x86_64 zlib-1.2.11-15.fc30.x86_64
(gdb) disassemble
Dump of assembler code for function nvme_pcie_qpair_submit_tracker:
   0x0000000000452430 <+0>:     push   %r12
   0x0000000000452432 <+2>:     push   %rbp
   0x0000000000452433 <+3>:     mov    %rdi,%rbp
   0x0000000000452436 <+6>:     push   %rbx
   0x0000000000452437 <+7>:     movzbl 0x1(%rsi),%eax
   0x000000000045243b <+11>:    lea    -0x58(%rdi),%rbx
   0x000000000045243f <+15>:    mov    (%rdi),%rdx
   0x0000000000452442 <+18>:    and    $0x3,%eax
   0x0000000000452445 <+21>:    cmp    $0x1,%al
   0x0000000000452447 <+23>:    jne    0x45244d <nvme_pcie_qpair_submit_tracker+29>
   0x0000000000452449 <+25>:    orb    $0x40,0xb(%rdi)
   0x000000000045244d <+29>:    movzwl 0x50(%rbx),%eax
   0x0000000000452451 <+33>:    shl    $0x6,%rax
   0x0000000000452455 <+37>:    add    0x10(%rbx),%rax
   0x0000000000452459 <+41>:    testb  $0x10,0x1871(%rdx)
   0x0000000000452460 <+48>:    jne    0x452518 <nvme_pcie_qpair_submit_tracker+232>
   0x0000000000452466 <+54>:    vmovdqu (%rsi),%xmm0
   0x000000000045246a <+58>:    vmovups %xmm0,(%rax)
   0x000000000045246e <+62>:    vmovdqu 0x10(%rsi),%xmm1
   0x0000000000452473 <+67>:    vmovups %xmm1,0x10(%rax)
   0x0000000000452478 <+72>:    vmovdqu 0x20(%rsi),%xmm2
   0x000000000045247d <+77>:    vmovups %xmm2,0x20(%rax)
   0x0000000000452482 <+82>:    vmovdqu 0x30(%rsi),%xmm3
   0x0000000000452487 <+87>:    vmovups %xmm3,0x30(%rax)
   0x000000000045248c <+92>:    movzwl 0x50(%rbx),%eax
   0x0000000000452490 <+96>:    add    $0x1,%eax
   0x0000000000452493 <+99>:    mov    %ax,0x50(%rbx)
   0x0000000000452497 <+103>:   cmp    0x48(%rbx),%ax
   0x000000000045249b <+107>:   je     0x452550 <nvme_pcie_qpair_submit_tracker+288>
   0x00000000004524a1 <+113>:   cmp    %ax,0x54(%rbx)
   0x00000000004524a5 <+117>:   je     0x452568 <nvme_pcie_qpair_submit_tracker+312>
   0x00000000004524ab <+123>:   movzbl 0x56(%rbx),%eax
   0x00000000004524af <+127>:   test   $0x2,%al
   0x00000000004524b1 <+129>:   je     0x4524c0 <nvme_pcie_qpair_submit_tracker+144>
   0x00000000004524b3 <+131>:   pop    %rbx
   0x00000000004524b4 <+132>:   pop    %rbp
   0x00000000004524b5 <+133>:   pop    %r12
   0x00000000004524b7 <+135>:   retq
   0x00000000004524b8 <+136>:   nopl   0x0(%rax,%rax,1)
   0x00000000004524c0 <+144>:   movzbl 0xb(%rbp),%edx
   0x00000000004524c4 <+148>:   test   $0x40,%dl
   0x00000000004524c7 <+151>:   jne    0x452508 <nvme_pcie_qpair_submit_tracker+216>
   0x00000000004524c9 <+153>:   mov    0x0(%rbp),%r12
   0x00000000004524cd <+157>:   test   $0x4,%al
   0x00000000004524cf <+159>:   jne    0x452590 <nvme_pcie_qpair_submit_tracker+352>
   0x00000000004524d5 <+165>:   sfence
   0x00000000004524d8 <+168>:   mov    %fs:0x0,%rax
   0x00000000004524e1 <+177>:   lea    -0x1e0(%rax),%rax
   0x00000000004524e8 <+184>:   movzwl 0x50(%rbx),%ecx
   0x00000000004524ec <+188>:   mov    %r12,(%rax)
   0x00000000004524ef <+191>:   mov    -0x58(%rbp),%rdx
   0x00000000004524f3 <+195>:   mov    %ecx,(%rdx)
   0x00000000004524f5 <+197>:   movq   $0x0,(%rax)
   0x00000000004524fc <+204>:   pop    %rbx
   0x00000000004524fd <+205>:   pop    %rbp
--Type <RET> for more, q to quit, c to continue without paging--
   0x00000000004524fe <+206>:   pop    %r12
   0x0000000000452500 <+208>:   retq
   0x0000000000452501 <+209>:   nopl   0x0(%rax)
   0x0000000000452508 <+216>:   and    $0xffffffbf,%edx
   0x000000000045250b <+219>:   pop    %rbx
   0x000000000045250c <+220>:   mov    %dl,0xb(%rbp)
   0x000000000045250f <+223>:   pop    %rbp
   0x0000000000452510 <+224>:   pop    %r12
   0x0000000000452512 <+226>:   retq
   0x0000000000452513 <+227>:   nopl   0x0(%rax,%rax,1)
   0x0000000000452518 <+232>:   cmpb   $0x0,0x120(%rbx)
   0x000000000045251f <+239>:   je     0x452466 <nvme_pcie_qpair_submit_tracker+54>
   0x0000000000452525 <+245>:   vmovdqu (%rsi),%xmm4
=> 0x0000000000452529 <+249>:   vmovups %xmm4,(%rax)
   0x000000000045252d <+253>:   vmovdqu 0x10(%rsi),%xmm5
   0x0000000000452532 <+258>:   vmovups %xmm5,0x10(%rax)
   0x0000000000452537 <+263>:   vmovdqu 0x20(%rsi),%xmm6
   0x000000000045253c <+268>:   vmovups %xmm6,0x20(%rax)
   0x0000000000452541 <+273>:   vmovdqu 0x30(%rsi),%xmm7
   0x0000000000452546 <+278>:   vmovups %xmm7,0x30(%rax)
   0x000000000045254b <+283>:   jmpq   0x45248c <nvme_pcie_qpair_submit_tracker+92>
   0x0000000000452550 <+288>:   xor    %eax,%eax
   0x0000000000452552 <+290>:   mov    %ax,0x50(%rbx)
   0x0000000000452556 <+294>:   xor    %eax,%eax
   0x0000000000452558 <+296>:   cmp    %ax,0x54(%rbx)
   0x000000000045255c <+300>:   jne    0x4524ab <nvme_pcie_qpair_submit_tracker+123>
   0x0000000000452562 <+306>:   nopw   0x0(%rax,%rax,1)
   0x0000000000452568 <+312>:   mov    $0x53c,%edx
   0x000000000045256d <+317>:   xor    %edi,%edi
   0x000000000045256f <+319>:   lea    0x12c190(%rip),%r8        # 0x57e706
   0x0000000000452576 <+326>:   xor    %eax,%eax
   0x0000000000452578 <+328>:   lea    0x12c591(%rip),%rcx        # 0x57eb10 <__func__.42574>
   0x000000000045257f <+335>:   lea    0x12c082(%rip),%rsi        # 0x57e608
   0x0000000000452586 <+342>:   callq  0x49c680 <spdk_log>
   0x000000000045258b <+347>:   jmpq   0x4524ab <nvme_pcie_qpair_submit_tracker+123>
   0x0000000000452590 <+352>:   mov    0x100(%rbx),%rdx
   0x0000000000452597 <+359>:   test   %rdx,%rdx
   0x000000000045259a <+362>:   je     0x4524d5 <nvme_pcie_qpair_submit_tracker+165>
   0x00000000004525a0 <+368>:   movzwl 0x50(%rbx),%edi
   0x00000000004525a4 <+372>:   mov    0x110(%rbx),%rsi
   0x00000000004525ab <+379>:   mov    (%rdx),%ecx
   0x00000000004525ad <+381>:   mov    %edi,%eax
   0x00000000004525af <+383>:   mov    %edi,(%rdx)
   0x00000000004525b1 <+385>:   mfence
   0x00000000004525b4 <+388>:   mov    (%rsi),%edx
   0x00000000004525b6 <+390>:   sub    %ecx,%eax
   0x00000000004525b8 <+392>:   sub    %edx,%edi
   0x00000000004525ba <+394>:   cmp    %ax,%di
   0x00000000004525bd <+397>:   jbe    0x4524d5 <nvme_pcie_qpair_submit_tracker+165>
   0x00000000004525c3 <+403>:   jmpq   0x4524b3 <nvme_pcie_qpair_submit_tracker+131>
End of assembler dump.
(gdb) bt full
#0  0x0000000000452529 in nvme_pcie_qpair_submit_tracker (qpair=qpair@entry=0x200023a17c98, tr=<optimized out>) at nvme_pcie.c:1329
        req = 0x200023a17a80
        pqpair = 0x200023a17c40
        ctrlr = 0x200023a17e40
        __func__ = "nvme_pcie_qpair_submit_tracker"
#1  0x0000000000453f60 in nvme_pcie_qpair_submit_request (qpair=0x200023a17c98, req=<optimized out>) at nvme_pcie.c:2274
        tr = 0x200016e2d000
        rc = 0
        ctrlr = 0x200023a17e40
        pqpair = 0x200023a17c40
        payload_type = <optimized out>
        sgl_supported = <optimized out>
        dword_aligned = true
#2  0x0000000000454a77 in _nvme_qpair_submit_request (req=0x200023a17a80, qpair=0x200023a17c98) at nvme_qpair.c:710
        child_req = <optimized out>
        tmp = <optimized out>
        ctrlr = 0x200023a17e40
        rc = 0
        cmd = <optimized out>
        child_req_failed = false
        rc = <optimized out>
        child_req = <optimized out>
        tmp = <optimized out>
        cmd = <optimized out>
        ctrlr = <optimized out>
        child_req_failed = <optimized out>
#3  nvme_qpair_submit_request (qpair=0x200023a17c98, req=0x200023a17a80) at nvme_qpair.c:770
        rc = <optimized out>
#4  0x0000000000448b1c in nvme_ctrlr_submit_admin_request (ctrlr=ctrlr@entry=0x200023a17e40, req=<optimized out>) at nvme_ctrlr.c:2876
No locals.
#5  0x00000000004456ad in nvme_ctrlr_cmd_identify (ctrlr=ctrlr@entry=0x200023a17e40, cns=cns@entry=1 '\001', cntid=cntid@entry=0, nsid=nsid@entry=0, payload=payload@entry=0x200023a18430,
    payload_size=payload_size@entry=4096, cb_fn=0x446e80 <nvme_ctrlr_identify_done>, cb_arg=0x200023a17e40) at nvme_ctrlr_cmd.c:157
        req = <optimized out>
        cmd = <optimized out>
#6  0x0000000000449e87 in nvme_ctrlr_identify (ctrlr=0x200023a17e40) at nvme_ctrlr.c:1379
        rc = <optimized out>
#7  nvme_ctrlr_process_init (ctrlr=ctrlr@entry=0x200023a17e40) at nvme_ctrlr.c:2630
        cc = {raw = 4587521, bits = {en = 1, reserved1 = 0, css = 0, mps = 0, ams = 0, shn = 0, iosqes = 6, iocqes = 4, reserved2 = 0}}
        csts = {raw = 1, bits = {rdy = 1, cfs = 0, shst = 0, nssro = 0, pp = 0, reserved1 = 0}}
        ready_timeout_in_ms = 7500
        rc = 0
        __func__ = "nvme_ctrlr_process_init"
#8  0x00000000004584b9 in nvme_ctrlr_poll_internal (probe_ctx=0xae7c30, ctrlr=0x200023a17e40) at nvme.c:1372
        rc = 0
        rc = <optimized out>
        __func__ = "nvme_ctrlr_poll_internal"
#9  spdk_nvme_probe_poll_async (probe_ctx=0xae7c30) at nvme.c:1372
        rc = 0
        ctrlr = 0x200023a17e40
        ctrlr_tmp = 0x0
#10 0x000000000041bc8c in bdev_nvme_async_poll (arg=0xae7750) at bdev_nvme.c:1737
        ctx = 0xae7750
        rc = <optimized out>
#11 0x000000000049e1f9 in thread_poll (now=1936876066474, max_msgs=0, thread=0xaa8570) at thread.c:646
        timer_rc = 0
        msg_count = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        poller = 0xae7fe0
        tmp = 0xac8f80
        critical_msg = <optimized out>
        rc = 0
        msg_count = <optimized out>
        poller = <optimized out>
        tmp = <optimized out>
        critical_msg = <optimized out>
        rc = <optimized out>
        poller_rc = <optimized out>
        timer_rc = <optimized out>
#12 spdk_thread_poll (thread=thread@entry=0xaa8570, max_msgs=max_msgs@entry=0, now=1936876066474) at thread.c:689
        orig_thread = 0x0
        rc = <optimized out>
#13 0x00000000004867b9 in _reactor_run (reactor=0xaa8200) at reactor.c:326
        thread = 0xaa8570
        tmp = 0xacc8c8
        lw_thread = 0xaa8898
        now = <optimized out>
        rc = <optimized out>
        thread = <optimized out>
        lw_thread = <optimized out>
        tmp = <optimized out>
        now = <optimized out>
        rc = <optimized out>
#14 reactor_run (arg=0xaa8200) at reactor.c:382
        reactor = <optimized out>
        thread = <optimized out>
        lw_thread = <optimized out>
        tmp = <optimized out>
        thread_name = "reactor_0\000\030\004\000\000\000\000\300\356(\004\000\000\000\000\330\016\071\004\000\000\000"
        __func__ = "reactor_run"
#15 0x0000000000486ce1 in spdk_reactors_start () at reactor.c:477
        reactor = <optimized out>
        tmp_cpumask = {str = '\000' <repeats 256 times>, cpus = '\000' <repeats 127 times>}
        i = <optimized out>
        current_core = 0
        rc = <optimized out>
        thread_name = "\340o\352\004\000\000\000\000\370\217\372\004\000\000\000\000\020\260\n\005\000\000\000\000(\320\032\005\000\000\000"
        __func__ = "spdk_reactors_start"
#16 0x0000000000485089 in spdk_app_start (opts=opts@entry=0x7fffffffe200, start_fn=start_fn@entry=0x416b10 <spdk_tgt_started>, arg1=arg1@entry=0x0) at app.c:691
        config = <optimized out>
        rc = 0
        tty = <optimized out>
        tmp_cpumask = {str = '\000' <repeats 256 times>, cpus = "\001", '\000' <repeats 126 times>}
        __func__ = "spdk_app_start"
#17 0x00000000004133b8 in main (argc=3, argv=0x7fffffffe3b8) at spdk_tgt.c:120
        opts = {name = 0x5730e0 "spdk_tgt", config_file = 0x0, json_config_file = 0x7fffffffe676 "k", json_config_ignore_errors = false, rpc_addr = 0x58a03d "/var/tmp/spdk.sock",
          reactor_mask = 0x58a1ab "0x1", tpoint_group_mask = 0x0, shm_id = -1, shutdown_cb = 0x0, usr1_handler = 0x0, enable_coredump = true, mem_channel = -1, master_core = -1, mem_size = -1,
          no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, hugedir = 0x0, print_level = SPDK_LOG_INFO, num_pci_addr = 0, pci_blacklist = 0x0, pci_whitelist = 0x0,
          iova_mode = 0x0, max_delay_us = 0, delay_subsystem_init = false, num_entries = 32768, env_context = 0x0, log = 0x0}
        rc = <optimized out>
(gdb)

```
Let me know if you need any additional info. :)

**Comment by jimharris** [comment]
@Seth5141 @karlatec what options do we pass to our QEMU VMs in the test pool?  I'd like @mikeBashStuff to try with those same options here. If he is building the app inside the VM, it shouldn't generate instructions that it can't execute.

**Comment by darsto** [comment]
@jimharris we don't use Q35 on CI, but I did use it locally and didn't see any problems. 

On some machines I see a warning from DPDK when building: "AVX512 support disabled because of binutils 2.30. See Bug 97" - this might be related.

**Comment by changpe1** [comment]
@jimharris @mikeBashStuff commit 44f69a9e already fixed this issue, but this patch didn't backport to LTS.

**Comment by changpe1** [comment]
See related issue #1362

**Comment by mikeBashStuff** [comment]
@changpe1 I am building spdk on the VM against the latest master which includes this particular fix.

 I tested it against different qemus (3.1.0, 4.2.0, 5.0.0) and with the same `-cpu|machine` args the Vagrant (`create_vbox.sh`) executes the qemu with, all with the same result. As a last resort, I removed support for CMB from the emulated nvme drives and now apps seem to work, i.e., SIGILL is not being sent out when they try to attach to the nvmes.

@darsto with the above in mind, can you please try to run your VM locally once again, but with the CMB enabled? Just to confirm that this indeed is the culprit here and not limited to my own setup. :)

**Comment by changpe1** [comment]
> @changpe1 I am building spdk on the VM against the latest master which includes this particular fix.
> 
> I tested it against different qemus (3.1.0, 4.2.0, 5.0.0) and with the same `-cpu|machine` args the Vagrant (`create_vbox.sh`) executes the qemu with, all with the same result. As a last resort, I removed support for CMB from the emulated nvme drives and now apps seem to work, i.e., SIGILL is not being sent out when they try to attach to the nvmes.
> 
> @darsto with the above in mind, can you please try to run your VM locally once again, but with the CMB enabled? Just to confirm that this indeed is the culprit here and not limited to my own setup. :)

Could you list the drive device ID in your VM? if it used a different device ID, we may need to add it in quirks.

**Comment by mikeBashStuff** [comment]
@changpe1 

Here's how they are defined for the qemu:
```
-drive
file=/tmp/qemu/nvme0.img,if=none,id=D0,format=raw
-device
nvme,drive=D0,serial=kaka-1717
-drive
file=/tmp/qemu/nvme1.img,if=none,id=D1,format=raw
-device
nvme,drive=D1,serial=kaka-3876
-drive
file=/tmp/qemu/nvme2.img,if=none,id=D2,format=raw
-device
nvme,drive=D2,serial=kaka-12125
-drive
file=/tmp/qemu/nvme3.img,if=none,id=D3,format=raw
-device
nvme,drive=D3,serial=kaka-1538
```

This is how they are seen inside the VM:
```
[root@fedora30-cloud-20264 ~]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     kaka-1717            QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
/dev/nvme1n1     kaka-3876            QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
/dev/nvme2n1     kaka-12125           QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
/dev/nvme3n1     kaka-1538            QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
[root@fedora30-cloud-20264 ~]#

```

**Comment by changpe1** [comment]
> @changpe1
> 
> Here's how they are defined for the qemu:
> 
> ```
> -drive
> file=/tmp/qemu/nvme0.img,if=none,id=D0,format=raw
> -device
> nvme,drive=D0,serial=kaka-1717
> -drive
> file=/tmp/qemu/nvme1.img,if=none,id=D1,format=raw
> -device
> nvme,drive=D1,serial=kaka-3876
> -drive
> file=/tmp/qemu/nvme2.img,if=none,id=D2,format=raw
> -device
> nvme,drive=D2,serial=kaka-12125
> -drive
> file=/tmp/qemu/nvme3.img,if=none,id=D3,format=raw
> -device
> nvme,drive=D3,serial=kaka-1538
> ```
> 
> This is how they are seen inside the VM:
> 
> ```
> [root@fedora30-cloud-20264 ~]# nvme list
> Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
> ---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
> /dev/nvme0n1     kaka-1717            QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
> /dev/nvme1n1     kaka-3876            QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
> /dev/nvme2n1     kaka-12125           QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
> /dev/nvme3n1     kaka-1538            QEMU NVMe Ctrl                           1           8.59  GB /   8.59  GB    512   B +  0 B   1.0
> [root@fedora30-cloud-20264 ~]#
> ```

I mean the PCI device ID, such as 0x5845 for QEMU quirks for existing code, if it was already in the quirks list, I think the issue should already be fixed.

**Comment by mikeBashStuff** [comment]
@changpe1 Oh, ok, thought you meant the qemu's ids. Here you go:

```
[root@fedora30-cloud-20264 spdk]# for d in /sys/bus/pci/drivers/nvme/0000*; do echo "${d##*/}:$(<"$d/device"):$(<"$d/vendor")"; done
0000:00:04.0:0x5845:0x8086
0000:00:05.0:0x5845:0x8086
0000:00:06.0:0x5845:0x8086
0000:00:07.0:0x5845:0x8086

```

**Comment by changpe1** [comment]
> @changpe1 Oh, ok, thought you meant the qemu's ids. Here you go:
> 
> ```
> [root@fedora30-cloud-20264 spdk]# for d in /sys/bus/pci/drivers/nvme/0000*; do echo "${d##*/}:$(<"$d/device"):$(<"$d/vendor")"; done
> 0000:00:04.0:0x5845:0x8086
> 0000:00:05.0:0x5845:0x8086
> 0000:00:06.0:0x5845:0x8086
> 0000:00:07.0:0x5845:0x8086
> ```

Yeah, I believe this issue has been fixed by me, let me try again.

**Comment by changpe1** [comment]
@mikeBashStuff issue #1362 is also reported by you, I've verified again, it works well in my VM, can you try again with master SPDK?

**Comment by mikeBashStuff** [comment]
@changpe1 Still the same. It works only when I remove `cmb_size_mb` arg from the nvme drives.

**Comment by wawryk** [comment]
@mikeBashStuff as I can see You use qemu-4.2.0
in our test pool we use qemu-5.0.0 from here: https://github.com/spdk/qemu/tree/spdk-5.0.0
maybe wrong qemu version caused Your issue ?

**Comment by mikeBashStuff** [comment]
@wawryk :)
>I tested it against different qemus (3.1.0, 4.2.0, 5.0.0) and with the same -cpu|machine args the Vagrant (create_vbox.sh) executes the qemu with, all with the same result.

I don't think there are any VMs on the CI which have CMB enabled on their nvme drives though.

**Comment by jimharris** [comment]
Oh - I didn't know we were using CMB here.

This is related to the issue we tried to fix a couple of weeks ago. It seems that even for direct assignment (rather than explicit SSE) the compiler will still emit SSE instructions. I think for CMB, we need to implement an inline memory copy routine that only copies 4 bytes at a time into the SQ.

I'll create a patch for you to test.

**Comment by changpe1** [comment]
> Oh - I didn't know we were using CMB here.
> 
> This is related to the issue we tried to fix a couple of weeks ago. It seems that even for direct assignment (rather than explicit SSE) the compiler will still emit SSE instructions. I think for CMB, we need to implement an inline memory copy routine that only copies 4 bytes at a time into the SQ.
> 
> I'll create a patch for you to test.

I see, I used Fedora 30 image, it may still happen if we used other images.

**Comment by jimharris** [comment]
Please try https://review.spdk.io/gerrit/c/spdk/spdk/+/3135.

**Comment by mikeBashStuff** [comment]
@jimharris With this patch everything works like a charm, thanks! \o/

**Comment by mikeBashStuff** [comment]
Fix merged, closing this issue.
