### ISSUE TITLE
[idxd_perf] idxd_perf keeps looping without results

### ISSUE THREAD

**Issue by ye1xchen** [spdk/spdk#2329]
# Bug report

./build/examples/idxd_perf keeps looping without results.

## Expected Behavior

idxd_perf exits normally.

## Current Behavior

./build/examples/idxd_perf keeps looping without results.

## Steps to Reproduce

1.  ./configure --with-idxd
2.  make -j
3. accel-config disable-wq dsa0/wq0.1
accel-config disable-device dsa0
accel-config config-wq --group-id=0 --mode=dedicated --wq-size=16 --type=user --name="MyApp1" --priority=10 --block-on-fault=1 dsa0/wq0.1
accel-config config-engine dsa0/engine0.1 --group-id=0
accel-config enable-device dsa0
accel-config enable-wq dsa0/wq0.1
4.  ./build/examples/idxd_perf  -q 1 -o 4096 -t 5 -w copy -k

## Context (Environment including OS version, SPDK version, etc.)
fedora 32
Latest SPDK master

**Comment by yidong0635** [comment]
Just have a quick review about this, drain io can't exit with endless loop,
in spdk_idxd_process_events : IDXD_COMPLETION(op->hw.status) always false , and break foreach chan->ops_outstanding with current_queue_depth always above 0.
No sure if there's any implements need to do,  there's only comments left:
/*
 * oldest locations are at the head of the list so if
 * we've polled a location that hasn't completed, bail
 * now as there are unlikely to be any more completions.
 */

**Comment by benlwalker** [comment]
Should be fixed by https://github.com/spdk/spdk/commit/c1ec9241665e4f8bb9cc4431d2e2befcf447654c which was merged yesterday

**Comment by peluse** [comment]
@ye1xchen I hav a request for you, I don't believe we have any idxd kernel usage tests in CI at all.  I assume you ran this manually?  Can you please submit a patch and add this (maybe expanded a bit) so we get some coverage there?

**Comment by yidong0635** [comment]
@peluse thanks, maybe  I or @ye1xchen will add this later, but this test depends on  special HW config.
@benlwalker  sorry to say that,  doesn't fix this issue.

**Comment by ye1xchen** [comment]
@benlwalker Thanks for your reply, but this issue still exists with latest spdk.

**Comment by peluse** [comment]
Yeah, I was wondering with perf that was in master when you ran this (I assume) we auto-limited teh Q depth to avoid busy.  I don't think this is a medium based on HW availability, @benlwalker  I can pick this up but won't be able to look at until end of next week if that works.

**Comment by benlwalker** [comment]
I see a minor bug in idxd_perf that I'll submit a fix for, but it isn't related to the problem here. When I run idxd_perf against kernel DSA we simply never get any completions at all.

**Comment by benlwalker** [comment]
This series gets the tool to stop hanging. I'm still not seeing the correct behavior but getting closer: https://review.spdk.io/gerrit/c/spdk/spdk/+/11209

**Comment by benlwalker** [comment]
Ok, I updated https://review.spdk.io/gerrit/c/spdk/spdk/+/11209 and now it's working for me.

**Comment by yidong0635** [comment]
here the HW may damaged . After applying your patches:
```
Thread 1 "idxd_perf" received signal SIGINT, Interrupt.
0x000000000041fa0e in spdk_idxd_process_events (chan=0x9e6050) at idxd.c:1332
1332            return rc;
(gdb) s
idxd_chan_poll (chan=chan@entry=0x9fd620) at perf.c:767
767             if (rc < 0) {
(gdb)
771             if (!TAILQ_EMPTY(&chan->resubmits)) {
(gdb)
drain_io (t=0x9fd620) at perf.c:510
510             while (t->current_queue_depth > 0) {
(gdb)
511                     idxd_chan_poll(t);
(gdb)
idxd_chan_poll (chan=chan@entry=0x9fd620) at perf.c:766
766             rc = spdk_idxd_process_events(chan->ch);
(gdb)
spdk_idxd_process_events (chan=0x9e6050) at idxd.c:1259
1259            TAILQ_FOREACH_SAFE(op, &chan->ops_outstanding, link, tmp) {
(gdb)
1260                    if (IDXD_COMPLETION(op->hw.status)) {
(gdb)
1328            if (chan->batch) {
(gdb)
1332            return rc;
(gdb)
idxd_chan_poll (chan=chan@entry=0x9fd620) at perf.c:767
767             if (rc < 0) {
(gdb)
771             if (!TAILQ_EMPTY(&chan->resubmits)) {
(gdb)
drain_io (t=0x9fd620) at perf.c:510
510             while (t->current_queue_depth > 0) {
(gdb)
511                     idxd_chan_poll(t);
(gdb)
idxd_chan_poll (chan=chan@entry=0x9fd620) at perf.c:766
766             rc = spdk_idxd_process_events(chan->ch);
(gdb)
spdk_idxd_process_events (chan=0x9e6050) at idxd.c:1259
1259            TAILQ_FOREACH_SAFE(op, &chan->ops_outstanding, link, tmp) {
(gdb)
1260                    if (IDXD_COMPLETION(op->hw.status)) {
(gdb)
1328            if (chan->batch) {
(gdb)
1332            return rc;
(gdb)
idxd_chan_poll (chan=chan@entry=0x9fd620) at perf.c:767
767             if (rc < 0) {
(gdb)
771             if (!TAILQ_EMPTY(&chan->resubmits)) {
(gdb)
drain_io (t=0x9fd620) at perf.c:510
510             while (t->current_queue_depth > 0) {
(gdb)
511                     idxd_chan_poll(t);
(gdb)
idxd_chan_poll (chan=chan@entry=0x9fd620) at perf.c:766
766             rc = spdk_idxd_process_events(chan->ch);
(gdb)
spdk_idxd_process_events (chan=0x9e6050) at idxd.c:1259
1259            TAILQ_FOREACH_SAFE(op, &chan->ops_outstanding, link, tmp) {
(gdb)
```

And I just try this before  to force to make it out:
```
diff --git a/examples/idxd/perf/perf.c b/examples/idxd/perf/perf.c
index 3bbc33f44..24c83f62b 100644
--- a/examples/idxd/perf/perf.c
+++ b/examples/idxd/perf/perf.c
@@ -502,12 +502,18 @@ _get_task(struct idxd_chan_entry *t)
        return task;
 }

-static void
+static int
 drain_io(struct idxd_chan_entry *t)
 {
+       int rc = 0;
        while (t->current_queue_depth > 0) {
-               spdk_idxd_process_events(t->ch);
+               rc = spdk_idxd_process_events(t->ch);
+               if(rc < 0){
+                       break;
+               }
        }
+
+       return rc;
 }

 /* Submit one operation using the same idxd task that just completed. */
@@ -787,6 +793,7 @@ static int
 work_fn(void *arg)
 {
        uint64_t tsc_end;
+       int rc = 0;
        struct worker_thread *worker = (struct worker_thread *)arg;
        struct idxd_chan_entry *t = NULL;

@@ -818,7 +825,10 @@ work_fn(void *arg)
        while (t != NULL) {
                /* begin to drain io */
                t->is_draining = true;
-               drain_io(t);
+               rc = drain_io(t);
+               if(rc < 0){
+                       break;
+               }
                t = t->next;
        }


diff --git a/lib/idxd/idxd.c b/lib/idxd/idxd.c
index cc18ad156..836ddc95e 100644
--- a/lib/idxd/idxd.c
+++ b/lib/idxd/idxd.c
@@ -1274,6 +1274,8 @@ spdk_idxd_process_events(struct spdk_idxd_io_channel *chan)
                         * we've polled a location that hasn't completed, bail
                         * now as there are unlikely to be any more completions.
                         */
+                       rc = -EINVAL;
+                       fprintf(stderr, "bailout the completion for hw status error\n");
                        break;
                }
        }

```

**Comment by peluse** [comment]
@yidong0635 can you try this patch real quick? We've been dealing with lots of similar issues over the last few days and Ben is pretty busy today. https://review.spdk.io/gerrit/c/spdk/spdk/+/11212/9

**Comment by yidong0635** [comment]
@peluse @benlwalker  we are all here waiting for your patches, and local HW ENV has something wrong,  it's in urgent recovering. Keep your updating, We will verify it ASAP.

**Comment by ye1xchen** [comment]
I retried with Latest SPDK, but this issue still exists.
Maybe local HW ENV still has something wrong, and I think idxd_perf should exit with an error message instead of looping.

add dmesg log:
...
[  770.212910] idxd 0000:6a:01.0: idxd_cmd_exec: sending cmd: 0x6 op: 0x1
[  770.213145] idxd 0000:6a:01.0: WQ 1 enabled
[  793.605666] idxd 0000:6a:01.0: idxd_cdev_open called: 0
[  793.605685] idxd 0000:6a:01.0: idxd_cdev_mmap called
[  793.669158] IOMMU: dmar15: Page request without PASID
[  793.669166] dmar15: Invalid page request: 6a080001 2000003e9007
[  793.669621] idxd 0000:6a:01.0: err[0]: 0x0000000300011a2d
[  793.669635] idxd 0000:6a:01.0: err[1]: 0x0000000000000000
[  793.669639] idxd 0000:6a:01.0: err[2]: 0x00002000003e9000
[  793.669643] idxd 0000:6a:01.0: err[3]: 0x0000000000000000
[  793.669652] idxd 0000:6a:01.0: err[0]: 0x0000000300011a2c
[  793.669655] idxd 0000:6a:01.0: err[1]: 0x0000000000000000
[  793.669658] idxd 0000:6a:01.0: err[2]: 0x00002000003e9000
[  793.669661] idxd 0000:6a:01.0: err[3]: 0x0000000000000000

**Comment by peluse** [comment]
@benlwalker said its working for him.  Which commit are you using @ye1xchen and I assume its still an issue? I can try tomorrow and see how it works here.

**Comment by ye1xchen** [comment]
I retried with Latest SPDK today, but this issue still exists. @peluse  @benlwalker maybe we can make an meeting to show you the specific steps and output.

**Comment by wanqunintel** [comment]
@peluse did you have time to look into this issue on your environment? The error log shows as follows when running idxd_perf tool with command ./build/examples/idxd_perf -q 1 -o 4096 -t 5 -w copy -k
[ 793.669158] IOMMU: dmar15: Page request without PASID
[ 793.669166] dmar15: Invalid page request: 6a080001 2000003e9007

**Comment by wanqunintel** [comment]
spdk commit: 900d049925f0e2f751293958c4458544bf7c88be

**Comment by peluse** [comment]
not yet, will today though.  thanks for the reminder

**Comment by peluse** [comment]
@wanqunintel So I can't repro on my system but I do get an error with asan enabled and will file that separately but first since your HW may be suspect can you try grabbing master and running with accel_perf instead? It has a ton more test time than either idxd_perf or kernel mode.  Let's start with something that works on your system and see if we can't work our way into what doesn't.  accel_perf on master should be solid right now.

[peluse@fedora examples]$ sudo ./idxd_perf -q 1 -o 4096 -t 5 -w copy -k
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
idxd device=0x60c000000e80 is bound on core=0
SPDK Configuration:
Core mask:      0x1

Idxd Perf Configuration:
Workload Type:   copy
Transfer size:   4096 bytes
Queue depth:     1
Allocated depth: 1
Run time:        5 seconds
Verify:          No

Starting thread on core 0

IDXD_ChanID   Core      Transfers      Bandwidth     Failed     Miscompares
------------------------------------------------------------------------
         0    0         xxx/s      xxx MiB/s      0           0
=========================================================================
Total:                   xxx/s      xxx MiB/s     0           0


=================================================================
==30214==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6528 byte(s) in 128 object(s) allocated from:
    #0 0x7fb2e2c5e8f7 in strdup (/usr/lib64/libasan.so.6+0x598f7)
    #1 0x7fb2e2bec886 in add_group (/usr/lib64/libaccel-config.so.1+0x6886)

Direct leak of 5632 byte(s) in 184 object(s) allocated from:
    #0 0x7fb2e2cb391f in __interceptor_malloc (/usr/lib64/libasan.so.6+0xae91f)
    #1 0x7fb2e26e05bc in __scandir64_tail (/usr/lib64/libc.so.6+0xd95bc)

Direct leak of 384 byte(s) in 8 object(s) allocated from:
    #0 0x7fb2e2c5e8f7 in strdup (/usr/lib64/libasan.so.6+0x598f7)
    #1 0x7fb2e2bec47c in add_wq (/usr/lib64/libaccel-config.so.1+0x647c)

Direct leak of 64 byte(s) in 32 object(s) allocated from:
    #0 0x7fb2e2c5e8f7 in strdup (/usr/lib64/libasan.so.6+0x598f7)
    #1 0x7fb2e2beb37f in accfg_get_param_str.constprop.0 (/usr/lib64/libaccel-config.so.1+0x537f)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fb2e2cb3ad7 in calloc (/usr/lib64/libasan.so.6+0xaead7)
    #1 0x418cc8 in kernel_idxd_wq_config /home/peluse/spdk/lib/idxd/idxd_kernel.c:265
    #2 0x4192b7 in _kernel_idxd_probe /home/peluse/spdk/lib/idxd/idxd_kernel.c:332
    #3 0x41938b in kernel_idxd_probe /home/peluse/spdk/lib/idxd/idxd_kernel.c:350
    #4 0x40dba9 in spdk_idxd_probe /home/peluse/spdk/lib/idxd/idxd.c:346
    #5 0x4074f3 in idxd_init /home/peluse/spdk/examples/idxd/perf/perf.c:174
    #6 0x40bd11 in main /home/peluse/spdk/examples/idxd/perf/perf.c:969
    #7 0x7fb2e263455f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2d55f)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7fb2e2cb3ad7 in calloc (/usr/lib64/libasan.so.6+0xaead7)
    #1 0x418b64 in kernel_idxd_wq_config /home/peluse/spdk/lib/idxd/idxd_kernel.c:254
    #2 0x4192b7 in _kernel_idxd_probe /home/peluse/spdk/lib/idxd/idxd_kernel.c:332
    #3 0x41938b in kernel_idxd_probe /home/peluse/spdk/lib/idxd/idxd_kernel.c:350
    #4 0x40dba9 in spdk_idxd_probe /home/peluse/spdk/lib/idxd/idxd.c:346
    #5 0x4074f3 in idxd_init /home/peluse/spdk/examples/idxd/perf/perf.c:174
    #6 0x40bd11 in main /home/peluse/spdk/examples/idxd/perf/perf.c:969
    #7 0x7fb2e263455f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2d55f)

SUMMARY: AddressSanitizer: 12744 byte(s) leaked in 354 allocation(s).
[peluse@fedora examples]$

**Comment by ye1xchen** [comment]
@peluse  running accel_perf without error as follows:
[root@waikikibeach68 spdk]# build/examples/accel_perf -q 32 -o 4096 -t 5 -w copy
SPDK Configuration:
Core mask:      0x1

Accel Perf Configuration:
Workload Type:  copy
Transfer size:  4096 bytes
Queue depth:    32
Allocate depth: 32
# threads/core: 1
Run time:       5 seconds
Verify:         No

[2022-03-21 17:24:28.035623] Starting SPDK v22.05-pre git sha1 586d1d657 / DPDK 21.11.0 initialization...
[2022-03-21 17:24:28.035747] [ DPDK EAL parameters: [2022-03-21 17:24:28.035768] (null) [2022-03-21 17:24:28.035781] --no-shconf [2022-03-21 17:24:28.035793] -c 0x1 [2022-03-21 17:24:28.035805] --huge-unlink [2022-03-21 17:24:28.035817] --log-level=lib.eal:6 [2022-03-21 17:24:28.035829] --log-level=lib.cryptodev:5 [2022-03-21 17:24:28.035840] --log-level=user1:6 [2022-03-21 17:24:28.035855] --base-virtaddr=0x200000000000 [2022-03-21 17:24:28.035869] --match-allocations [2022-03-21 17:24:28.035884] --file-prefix=spdk_pid1296102 [2022-03-21 17:24:28.035896] ]
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-03-21 17:24:28.176783] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-03-21 17:24:28.360503] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
[2022-03-21 17:24:28.360560] accel_engine.c: 558:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Running for 5 seconds...
[2022-03-21 17:24:28.361305] accel_perf.c: 623:identify_accel_engine_usage: *WARNING*: The selected workload is not natively supported by the current engine
[2022-03-21 17:24:28.361324] accel_perf.c: 624:identify_accel_engine_usage: *WARNING*: The software engine will be used instead.


Core,Thread   Transfers     Bandwidth     Failed     Miscompares
------------------------------------------------------------------------
0,0         10090604/s    39416 MiB/s      0           0
=========================================================================
Total:       10090604/s    39416 MiB/s     0           0

**Comment by wanqunintel** [comment]
@peluse , thank you for the quick response, after download the latest spdk code and run both idxd_perf and accel_perf, it looks like accel_perf can work normally with performance data printed out without error/failure. and idxd_perf will hang there until use the ctrl+c to kill it. The detailed log is attached for your reference. From the log that you have printed and compare it with my local environment's log, it seems the device ID is quite different, not sure what's this means and if it will cause any HW related issue?
My local environment: **idxd device=0xc4ad30 is bound on core=0**
Your environment: **idxd device=0x60c000000e80 is bound on core=0**
[issue_2329.txt](https://github.com/spdk/spdk/files/8313272/issue_2329.txt)

BTW: Since our HW and your HW maybe different, If this is HW issue, do you have any insight how to debug or check on it? Thank you again.

**Comment by peluse** [comment]
Hi, as mentioned in email the line below (from accel_perf)

[2022-03-21 21:14:05.766174] accel_perf.c: 623:identify_accel_engine_usage: *WARNING*: The selected workload is not natively supported by the current engine

tells you that you are not using HW acceleration.  In this case it's because with accel_perf you have to start the app with --wait-for-rpc and send the init idxd rpc followed by framework init (shown below) or start with a json file that init's the accel_fw with a HW engine.  idxd_perf is written only for idxd so no init is needed, accel_erf can run with any available HW engine so you need to init the one(s) you want to use

./scripts/rpc.py idxd_scan_accel_engine -c 0
./scripts/rpc.py framework_start_init

**Comment by ye1xchen** [comment]
thanks @peluse . I retry accel_perf, After running "./scripts/rpc.py idxd_scan_accel_engine -c 0; ./scripts/rpc.py framework_start_init", found message "**no available idxd devices**" . And when using "./scripts/rpc.py idxd_scan_accel_engine -c 0 **-k**; ./scripts/rpc.py framework_start_init " instead, accel_perf will keep looping without results.
 
Detailed output information is as follows：
 build/examples/accel_perf -q 32 -o 4096 -t 5 -w copy --wait-for-rpc
./scripts/rpc.py idxd_scan_accel_engine -c 0
./scripts/rpc.py framework_start_init
......
[2022-03-22 13:00:40.723972] accel_engine_idxd.c: 417:accel_engine_idxd_init: *NOTICE*: **no available idxd devices**
Running for 5 seconds...
[2022-03-22 13:00:40.724544] accel_perf.c: 623:identify_accel_engine_usage: *WARNING*: The selected workload is not natively supported by the current engine
[2022-03-22 13:00:40.724561] accel_perf.c: 624:identify_accel_engine_usage: *WARNING*: The software engine will be used instead.


Core,Thread   Transfers     Bandwidth     Failed     Miscompares
------------------------------------------------------------------------
0,0         10132876/s    39581 MiB/s      0           0
=========================================================================
Total:       10132876/s    39581 MiB/s     0           0

[root@waikikibeach68 spdk]# build/examples/accel_perf -q 32 -o 4096 -t 5 -w copy --wait-for-rpc 
./scripts/rpc.py idxd_scan_accel_engine -c 0 **-k**
./scripts/rpc.py framework_start_init
......
[2022-03-22 13:01:46.254986] accel_engine_idxd_rpc.c:  70:rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD kernel with config #0
[2022-03-22 13:01:58.674978] accel_engine.c: 558:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-03-22 13:01:58.678266] idxd_kernel.c: 134:dsa_setup_single_wq: *NOTICE*: alloc wq 1 shared 0 size 16 addr 0x7f18de563000 batch sz 0x400 xfer sz 0x80000000
[2022-03-22 13:01:58.678384] idxd_kernel.c: 336:_kernel_idxd_probe: *NOTICE*: Successfully got an kernel device=0x2594ca0
[2022-03-22 13:01:58.705024] accel_engine_idxd.c: 422:accel_engine_idxd_init: *NOTICE*: Accel engine updated to use IDXD DSA engine.
Running for 5 seconds...

**Comment by peluse** [comment]
@ye1xchen  are you working with @wanqunintel ? We're exchanging emails now.  Please sync with her.

**Comment by ye1xchen** [comment]
validation with Latest SPDK master(commit 68184a50306837386008844698fcaf236659041f), the error is different, close it, and open new issue https://github.com/spdk/spdk/issues/2503
