### ISSUE TITLE
vhost: can not clean vhost scsi/blk controller during vhost subsystem finish progress

### ISSUE THREAD

**Issue by v1c77** [spdk/spdk#2538]
# Bug report

The vdev->vsessions was not cleared before unregister.

lib/vhost/vhost.c
```
int
vhost_dev_unregister(struct spdk_vhost_dev *vdev)
{
	if (!TAILQ_EMPTY(&vdev->vsessions)) {
		SPDK_ERRLOG("Controller %s has still valid connection.\n", vdev->name);
		return -EBUSY;
	}
```
vhost.c:1015] [SPDK/vhost_dev_unregister] Controller vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0 has still val
id connection.

## Expected Behavior
Uninstall the vhost bdev as expected.

## Possible Solution
I have a test patch to clean vsession list at the end of the finish step,  but there seem to be some side effects:

```
diff --git a/lib/vhost/vhost.c b/lib/vhost/vhost.c
index 415595409d..d88822be73 100644
--- a/lib/vhost/vhost.c
+++ b/lib/vhost/vhost.c
@@ -1704,15 +1704,21 @@ static void *
 session_shutdown(void *arg)
 {
        struct spdk_vhost_dev *vdev = NULL;
-       struct spdk_vhost_session *vsession;
+       struct spdk_vhost_session *vsession, *tmp_vsession;
 
        TAILQ_FOREACH(vdev, &g_vhost_devices, tailq) {
                pthread_mutex_lock(&g_vhost_mutex);
-               TAILQ_FOREACH(vsession, &vdev->vsessions, tailq) {
-                       if (vsession->started) {
-                               _stop_session(vsession);
-                       }
-               }
+
+        for (vsession = TAILQ_FIRST(&vdev->vsessions); vsession != NULL; vsession = tmp_vsession) {
+            tmp_vsession = TAILQ_NEXT(vsession, tailq);
+            if (vsession->started) {
+                _stop_session(vsession);
+            }
+            TAILQ_REMOVE(&vsession->vdev->vsessions, vsession, tailq);
+            // free(vsession->name);
+               free(vsession);
+        }
+
                pthread_mutex_unlock(&g_vhost_mutex);
                vhost_driver_unregister(vdev->path);
                vdev->registered = false;
```

## Steps to Reproduce
1. storage app with spdk(version v21.10.x) embeded, create a vhost-user-scsi controller bdev. 

2. connect from frontend ,  eg:
```
qemu-kvm --enable-kvm -cpu host -smp 2 -m 1G \
    -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 \
    -drive file=guest_os_image.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0  \
    -device vhost-user-scsi-pci,chardev=drive-vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0,id=scsi0,bus=pci.0,addr=0x9,num_queues=1,bootindex=1 \
    -chardev socket,id=drive-vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0,path=/var/run/spdk/vhost/vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0 \
    ...
```

3.  call `spdk_subsystem_fini` and wait the app to stop.

```
I0530 15:42:13.402910  5388 vhost_scsi.c:1552] [SPDK/destroy_session_poller_cb] vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0s0: stopping poller on lcore -1
E0530 15:42:13.403192 39133 vhost.c:1067] [SPDK/wait_for_semaphore] Done waiting for event: vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0s0: stop session rc: 0.
I0530 15:42:13.403213 39133 vhost.c:1245] [SPDK/_stop_session] vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0s0: end to stop session
I0530 15:42:13.403286 39133 spdk.cc:206] [DPDK] VHOST_CONFIG: free connfd = 386 for device '/var/lib/spdk/vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0'
I0530 15:42:13.403299 39133 spdk.cc:206] [DPDK] VHOST_CONFIG: /var/lib/spdk/vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0: destroying device, vid: 0 flags: 0x23 dev: 0x2000114b0700
I0530 15:42:13.403313 39133 spdk.cc:206] [DPDK] VHOST_CONFIG: /var/lib/spdk/vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0: unmap all memory, vid: 0
I0530 15:42:13.403741 39133 vhost.c:1721] [SPDK/session_shutdown] Exiting
E0530 15:42:13.403861  5388 vhost.c:1015] [SPDK/vhost_dev_unregister] Controller vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0 has still valid connection.  <------ *HERE*
```

## Context (Environment including OS version, SPDK version, etc.)
spdk version:  v21.10.x & master

**Comment by Comphix** [comment]
Have you tried the latest SPDK v22.05 version?

**Comment by v1c77** [comment]
The logic of session_shutdown has no difference between v21.10 and  v22.05 or master. @Comphix

**Comment by jimharris** [comment]
> ## Steps to Reproduce
> 1. storage app with spdk(version v21.10.x) embeded, create a vhost-user-scsi controller bdev.
> 2. connect from frontend ,  eg:
> 
> ```
> qemu-kvm --enable-kvm -cpu host -smp 2 -m 1G \
>     -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 \
>     -drive file=guest_os_image.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0  \
>     -device vhost-user-scsi-pci,chardev=drive-vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0,id=scsi0,bus=pci.0,addr=0x9,num_queues=1,bootindex=1 \
>     -chardev socket,id=drive-vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0,path=/var/run/spdk/vhost/vhost-scsi.74a070ff-1a75-4a05-addc-6a55c7732c52.scsi0 \
>     ...
> ```
> 
>  3. call `spdk_subsystem_fini` and wait the app to stop.
> 

Hi @v1c77,

Please share more details (including code snippets) from your storage app.  I'm not aware of this issue being seen at all with the upstream SPDK applications.  So we need to understand how your app differs from the upstream SPDK applications.

Thanks,

Jim

**Comment by v1c77** [comment]
@jimharris @Comphix  I reproduced this issue on SPDK v21.10  with the default vhost app yesterday:

1. create a  vhost  backend
```
HUGEMEM=4096 scripts/setup.sh
build/bin/vhost -S /var/tmp -m 0x3 -L all
```
2. create controller and bdev
```
scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
scripts/rpc.py vhost_create_scsi_controller --cpumask 0x1 vhost.0
scripts/rpc.py vhost_scsi_controller_add_target vhost.0 0 Malloc0
```

3.  connect to the controller

```
taskset -c 2,3  /usr/libexec/qemu-kvm  \
     --enable-kvm -cpu host -smp 2 -m 1G \
    -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 \
    -drive file=/tmp/CentOS-7-x86_64-GenericCloud.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 \
    -chardev socket,id=spdk_vhost_scsi0,path=/var/tmp/vhost.0 \
    -device vhost-user-scsi-pci,id=scsi0,chardev=spdk_vhost_scsi0,num_queues=2 \
    -vnc 0.0.0.0:0
```

4. ctrl-C the vhost app.

You can see the error about "Controller xxx has still valid connection"

```
VHOST_CONFIG: free connfd = 187 for device '/var/tmp/vhost.0'
[2022-06-01 02:07:47.374852] vhost_scsi.c:1482:destroy_session_poller_cb: *INFO*: vhost.0s0: stopping poller on lcore 0
[2022-06-01 02:07:47.385985] vhost.c:1668:session_shutdown: *INFO*: Exiting
[2022-06-01 02:07:47.386029] vhost.c:1009:vhost_dev_unregister: *ERROR*: Controller vhost.0 has still valid connection.
[2022-06-01 02:07:47.386052] lun.c: 403:bdev_event_cb: *NOTICE*: bdev name (Malloc0) received event(SPDK_BDEV_EVENT_REMOVE)
[2022-06-01 02:07:47.386071] vhost_scsi.c: 209:remove_scsi_tgt: *INFO*: vhost.0: removed target 'Target 0'
```

-------------------------------
But it does not appear on the latest main branch,  I  would test it on the main branch.

Thank you.
v1c77.

**Comment by changpe1** [comment]
> @jimharris @Comphix I reproduced this issue on SPDK v21.10 with the default vhost app yesterday:
> 
> 1. create a  vhost  backend
> 
> ```
> HUGEMEM=4096 scripts/setup.sh
> build/bin/vhost -S /var/tmp -m 0x3 -L all
> ```
> 
> 2. create controller and bdev
> 
> ```
> scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
> scripts/rpc.py vhost_create_scsi_controller --cpumask 0x1 vhost.0
> scripts/rpc.py vhost_scsi_controller_add_target vhost.0 0 Malloc0
> ```
> 
> 3. connect to the controller
> 
> ```
> taskset -c 2,3  /usr/libexec/qemu-kvm  \
>      --enable-kvm -cpu host -smp 2 -m 1G \
>     -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 \
>     -drive file=/tmp/CentOS-7-x86_64-GenericCloud.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 \
>     -chardev socket,id=spdk_vhost_scsi0,path=/var/tmp/vhost.0 \
>     -device vhost-user-scsi-pci,id=scsi0,chardev=spdk_vhost_scsi0,num_queues=2 \
>     -vnc 0.0.0.0:0
> ```
> 
> 4. ctrl-C the vhost app.
> 
> You can see the error about "Controller xxx has still valid connection"
> 
> ```
> VHOST_CONFIG: free connfd = 187 for device '/var/tmp/vhost.0'
> [2022-06-01 02:07:47.374852] vhost_scsi.c:1482:destroy_session_poller_cb: *INFO*: vhost.0s0: stopping poller on lcore 0
> [2022-06-01 02:07:47.385985] vhost.c:1668:session_shutdown: *INFO*: Exiting
> [2022-06-01 02:07:47.386029] vhost.c:1009:vhost_dev_unregister: *ERROR*: Controller vhost.0 has still valid connection.
> [2022-06-01 02:07:47.386052] lun.c: 403:bdev_event_cb: *NOTICE*: bdev name (Malloc0) received event(SPDK_BDEV_EVENT_REMOVE)
> [2022-06-01 02:07:47.386071] vhost_scsi.c: 209:remove_scsi_tgt: *INFO*: vhost.0: removed target 'Target 0'
> ```
> 
> But it does not appear on the latest main branch, I would test it on the main branch.
> 
> Thank you. v1c77.

The issue should be fixed via https://github.com/spdk/spdk/commit/ba32ee2b298ba4659eace1aed2826d0b9ef82fbf

**Comment by v1c77** [comment]
> The issue should be fixed via [ba32ee2](https://github.com/spdk/spdk/commit/ba32ee2b298ba4659eace1aed2826d0b9ef82fbf)

Thank you @changpe1  for the suggestion !  But still, log "valid connection" on this fix. 

```
[2022-06-01 02:42:17.009803] vhost_scsi.c:1488:destroy_session_poller_cb: *INFO*: vhost.0s0: stopping poller on lcore 0
VHOST_CONFIG: free connfd = 187 for device '/var/tmp/vhost.0'
[2022-06-01 02:42:17.021021] vhost.c:1679:session_shutdown: *INFO*: Exiting
[2022-06-01 02:42:17.021054] vhost.c:1009:vhost_dev_unregister: *ERROR*: Controller vhost.0 has still valid connection.
[2022-06-01 02:42:17.021073] lun.c: 403:bdev_event_cb: *NOTICE*: bdev name (Malloc0) received event(SPDK_BDEV_EVENT_REMOVE)
[2022-06-01 02:42:17.021084] vhost_scsi.c: 208:remove_scsi_tgt: *INFO*: removed target 'Target 0'
╭─root@dev-amd-5950x ~/proj/spdk  ‹ba32ee2b2›
```

I guess the *expected behavior*  should be with logs just like below:
```
[2022-06-01 02:48:22.091828] vhost.c:1575:session_shutdown: *INFO*: Exiting
[2022-06-01 02:48:22.091883] vhost.c: 946:vhost_dev_unregister: *INFO*: Controller vhost.0: removed    # <---- *HERE* 
[2022-06-01 02:48:22.091947] lun.c: 427:bdev_event_cb: *NOTICE*: bdev name (Malloc0) received event(SPDK_BDEV_EVENT_REMOVE)
[2022-06-01 02:48:22.091976] vhost_scsi.c: 208:remove_scsi_tgt: *INFO*: removed target 'Target 0'
```

Also tested on `v22.05.x` : The log "valid connection" disappeared,  but  I'm not sure the controller has been deleted correctly.

**Comment by changpe1** [comment]
> > The issue should be fixed via [ba32ee2](https://github.com/spdk/spdk/commit/ba32ee2b298ba4659eace1aed2826d0b9ef82fbf)
> 
> Thank you @changpe1 for the suggestion ! But still, log "valid connection" on this fix.
> 
> ```
> [2022-06-01 02:42:17.009803] vhost_scsi.c:1488:destroy_session_poller_cb: *INFO*: vhost.0s0: stopping poller on lcore 0
> VHOST_CONFIG: free connfd = 187 for device '/var/tmp/vhost.0'
> [2022-06-01 02:42:17.021021] vhost.c:1679:session_shutdown: *INFO*: Exiting
> [2022-06-01 02:42:17.021054] vhost.c:1009:vhost_dev_unregister: *ERROR*: Controller vhost.0 has still valid connection.
> [2022-06-01 02:42:17.021073] lun.c: 403:bdev_event_cb: *NOTICE*: bdev name (Malloc0) received event(SPDK_BDEV_EVENT_REMOVE)
> [2022-06-01 02:42:17.021084] vhost_scsi.c: 208:remove_scsi_tgt: *INFO*: removed target 'Target 0'
> ╭─root@dev-amd-5950x ~/proj/spdk  ‹ba32ee2b2›
> ```
> 
> I guess the _expected behavior_ should be with logs just like below:
> 
> ```
> [2022-06-01 02:48:22.091828] vhost.c:1575:session_shutdown: *INFO*: Exiting
> [2022-06-01 02:48:22.091883] vhost.c: 946:vhost_dev_unregister: *INFO*: Controller vhost.0: removed    # <---- *HERE* 
> [2022-06-01 02:48:22.091947] lun.c: 427:bdev_event_cb: *NOTICE*: bdev name (Malloc0) received event(SPDK_BDEV_EVENT_REMOVE)
> [2022-06-01 02:48:22.091976] vhost_scsi.c: 208:remove_scsi_tgt: *INFO*: removed target 'Target 0'
> ```
> 
> Also tested on `v22.05.x` : The log "valid connection" disappeared, but I'm not sure the controller has been deleted correctly.

The error log is still there, so the issue is fixed with latest code.

**Comment by v1c77** [comment]
> > Also tested on `v22.05.x` : The log "valid connection" disappeared, but I'm not sure the controller has been deleted correctly.
> 
> The error log is still there, so the issue is fixed with latest code.

The controller still exists with the latest code.

@changpe1  After the commit https://github.com/spdk/spdk/commit/c706c20c50ad3cc5f0c5d7532473311ab6f65b37 ,
the check of  `vdev->pending_async_op_num`  in `vhost_user_dev_unregister` failed first and return, so the controller is not removed yet. Thus the log "has still valid connection" disappeared also.

You can apply the patch:
```
diff --git a/lib/vhost/rte_vhost_user.c b/lib/vhost/rte_vhost_user.c
index 09b524b15..29ec408f1 100644
--- a/lib/vhost/rte_vhost_user.c
+++ b/lib/vhost/rte_vhost_user.c
@@ -1785,6 +1785,7 @@ vhost_user_dev_unregister(struct spdk_vhost_dev *vdev)
        struct spdk_vhost_user_dev *user_dev = to_user_dev(vdev);
 
        if (user_dev->pending_async_op_num) {
+        SPDK_ERRLOG("Controller %s has still pending async operation.\n", vdev->name);
                return -EBUSY;
        }
```
The log showed up again:
```
^C[2022-06-01 05:17:50.435809] vhost_scsi.c:1492:destroy_session_poller_cb: *INFO*: vhost.0s0: stopping poller on lcore 0
VHOST_CONFIG: free connfd = 187 for device '/var/tmp/vhost.0'
[2022-06-01 05:17:50.447051] rte_vhost_user.c:1834:vhost_user_session_shutdown: *INFO*: Exiting
[2022-06-01 05:17:50.447092] rte_vhost_user.c:1760:vhost_user_dev_unregister: *ERROR*: controller vhost.0has still pending async operation.
[2022-06-01 05:17:50.447113] lun.c: 421:bdev_event_cb: *NOTICE*: bdev name (Malloc0) received event(SPDK_BDEV_EVENT_REMOVE)
[2022-06-01 05:17:50.447129] vhost_scsi.c: 208:remove_scsi_tgt: *INFO*: removed target 'Target 0'
```

**Comment by changpe1** [comment]
> pending_async_op_num

I see, since the QEMU connection is valid when you kill the vhost application, and the error log is our intention to warn users, so I don't think this is a bug.

Do you meet other errors like: can't exit the vhost application for the test case? if no, this is normal.

**Comment by v1c77** [comment]
Thanks for the information. The vhost app quit as normal. Please do not close this issue and I will test some more complicated cases.

**Comment by Comphix** [comment]
Hi @v1c77 , any update on recent tests regarding this issue?
