### ISSUE TITLE
[spdk/multipath]nvme_bdev_multipath_set_policy cause nvmf_tgt core dump

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2543]
# Bug report

nvme_bdev_multipath_set_policy cause nvmf_tgt core dump
## Expected Behavior

should work well
## Current Behavior

nvme_bdev_multipath_set_policy cause nvmf_tgt core dump
## Possible Solution

N/A yet
## Steps to Reproduce
on nvmf target
1. ./build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x3
2. ./scripts/rpc.py nvmf_create_transport -t tcp -o -u 8192
3. ./scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
4. ./scripts/rpc.py bdev_nvme_set_multipath_policy -b Malloc0 -p active_active
_Connection closed with partial response:_

then the nvmf_tgt app will core dump, error info as follows
_[2022-06-07 06:50:59.923859] Starting SPDK v22.05-pre git sha1 dacd8ec82 / DPDK 21.11.0 initialization...
[2022-06-07 06:50:59.923962] [ DPDK EAL parameters: [2022-06-07 06:50:59.923979] nvmf [2022-06-07 06:50:59.924014] -c 0x3 [2022-06-07 06:50:59.924023] --log-level=lib.eal:6 [2022-06-07 06:50:59.924032] --log-level=lib.cryptodev:5 [2022-06-07 06:50:59.924070] --log-level=user1:6 [2022-06-07 06:50:59.924081] --iova-mode=pa [2022-06-07 06:50:59.924093] --base-virtaddr=0x200000000000 [2022-06-07 06:50:59.924103] --match-allocations [2022-06-07 06:50:59.924112] --file-prefix=spdk0 [2022-06-07 06:50:59.924123] --proc-type=auto [2022-06-07 06:50:59.924134] ]
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-06-07 06:50:59.993808] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 2
[2022-06-07 06:51:00.150141] app.c: 449:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
[2022-06-07 06:51:00.150203] app.c: 453:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
[2022-06-07 06:51:00.150209] app.c: 455:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
[2022-06-07 06:51:00.150343] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-06-07 06:51:00.150344] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 1
[2022-06-07 06:51:00.150464] accel_engine.c: 842:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-06-07 06:51:04.565344] tcp.c: 639:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2022-06-07 06:51:11.378459] thread.c:2402:spdk_for_each_channel: *ERROR*: could not find io_device 0x2ae3b00
nvmf_tgt: thread.c:2403: spdk_for_each_channel: Assertion `false' failed.
Aborted (core dumped)_

## Context (Environment including OS version, SPDK version, etc.)

spdk commit: dacd8ec827fd98d3a8e67a922d7ea128ba61f2f7
OS: Fedora 29
Kernel: 5.5.1

**Comment by jimharris** [comment]
This code path wasn't checking that the specified bdev was actually an nvme bdev.

https://review.spdk.io/gerrit/c/spdk/spdk/+/12916 should fix it.

**Comment by wanqunintel** [comment]
@jimharris, this issue still exist with this patch. same error from nvmf_tgt
# ./build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x3
_[2022-06-07 22:39:51.038678] Starting SPDK v22.05-pre git sha1 dacd8ec82 / DPDK 21.11.0 initialization...
[2022-06-07 22:39:51.038795] [ DPDK EAL parameters: [2022-06-07 22:39:51.038810] nvmf [2022-06-07 22:39:51.038821] -c 0x3 [2022-06-07 22:39:51.038832] --log-level=lib.eal:6 [2022-06-07 22:39:51.038843] --log-level=lib.cryptodev:5 [2022-06-07 22:39:51.038855] --log-level=user1:6 [2022-06-07 22:39:51.038866] --iova-mode=pa [2022-06-07 22:39:51.038876] --base-virtaddr=0x200000000000 [2022-06-07 22:39:51.038888] --match-allocations [2022-06-07 22:39:51.038898] --file-prefix=spdk0 [2022-06-07 22:39:51.038909] --proc-type=auto [2022-06-07 22:39:51.038920] ]
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-06-07 22:39:51.109637] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 2
[2022-06-07 22:39:51.218029] app.c: 449:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
[2022-06-07 22:39:51.218105] app.c: 453:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
[2022-06-07 22:39:51.218111] app.c: 455:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
[2022-06-07 22:39:51.218217] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-06-07 22:39:51.218219] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 1
[2022-06-07 22:39:51.218335] accel_engine.c: 842:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-06-07 22:40:02.931077] tcp.c: 639:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2022-06-07 22:40:22.210199] thread.c:2402:spdk_for_each_channel: *ERROR*: could not find io_device 0x2d54010
nvmf_tgt: thread.c:2403: spdk_for_each_channel: Assertion `false' failed.
Aborted (core dumped)_

SPDK Commit: 1ca2de0b50579cd35b0e3639a976aac725bd7eb7

**Comment by jimharris** [comment]
> @jimharris, this issue still exist with this patch. same error from nvmf_tgt _# ./build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x3_ _[2022-06-07 22:39:51.038678] Starting SPDK v22.05-pre git sha1 [dacd8ec](https://github.com/spdk/spdk/commit/dacd8ec827fd98d3a8e67a922d7ea128ba61f2f7) / DPDK 21.11.0 initialization... 

I don't think you rebuilt nvmf_tgt.  Commit dacd8ec is a commit on master that would not include my patch.

> **SPDK Commit: 1ca2de0b50579cd35b0e3639a976aac725bd7eb7**

**Comment by wanqunintel** [comment]
my fault, just rebuild the code and the log is as follows, it should be fixed this issue, thank you, @jimharris 
_# ./build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x3
[2022-06-08 07:12:36.429289] Starting SPDK v22.09-pre git sha1 1ca2de0b5 / DPDK 21.11.0 initialization...
[2022-06-08 07:12:36.429403] [ DPDK EAL parameters: [2022-06-08 07:12:36.429419] nvmf [2022-06-08 07:12:36.429431] -c 0x3 [2022-06-08 07:12:36.429441] --log-level=lib.eal:6 [2022-06-08 07:12:36.429451] --log-level=lib.cryptodev:5 [2022-06-08 07:12:36.429461] --log-level=user1:6 [2022-06-08 07:12:36.429472] --iova-mode=pa [2022-06-08 07:12:36.429482] --base-virtaddr=0x200000000000 [2022-06-08 07:12:36.429492] --match-allocations [2022-06-08 07:12:36.429503] --file-prefix=spdk0 [2022-06-08 07:12:36.429514] --proc-type=auto [2022-06-08 07:12:36.429524] ]
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-06-08 07:12:36.495376] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 2
[2022-06-08 07:12:36.601654] app.c: 449:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
[2022-06-08 07:12:36.601729] app.c: 453:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
[2022-06-08 07:12:36.601735] app.c: 455:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
[2022-06-08 07:12:36.601787] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-06-08 07:12:36.601790] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 1
[2022-06-08 07:12:36.601901] accel_engine.c: 969:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-06-08 07:12:53.031668] tcp.c: 643:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2022-06-08 07:13:06.965976] bdev_nvme.c:3823:bdev_nvme_set_multipath_policy: *ERROR*: bdev Malloc0 is not registered in this module.

# ./scripts/rpc.py bdev_nvme_set_multipath_policy -b Malloc0 -p active_active
request:
{
  "name": "Malloc0",
  "policy": "active_active",
  "method": "bdev_nvme_set_multipath_policy",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -19,
  "message": "No such device"
}_

**Comment by changpe1** [comment]
patch has been merged and verified, closing it now.
