### ISSUE TITLE
[nvmf_vfio_user_fuzz] runtime error: left shift of 36560 by 16 places cannot be represented in type 'int'

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2858]
# Sighting report

Not sure if this should be a new issue or re-open of #2835 , but here goes...
https://review.spdk.io/gerrit/c/spdk/spdk/+/16029 fixed vfio fuzzer issue from #2835, but it's still failing.

See https://ci.spdk.io/public_build/autotest-per-patch_94050.html for details.

## Current Behavior

```
vfio_user.c:5370:49: runtime error: left shift of 36560 by 16 places cannot be represented in type 'int'
    #0 0x7f344c32c326 in map_admin_cmd_req /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5370
    #1 0x7f344c32d765 in handle_cmd_req /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5494
    #2 0x7f344c30bf65 in consume_admin_cmd /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:2467
    #3 0x7f344c30c8aa in consume_cmd /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:2504
    #4 0x7f344c30cc3d in handle_sq_tdbl_write /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:2542
    #5 0x7f344c32edc7 in nvmf_vfio_user_sq_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5639
    #6 0x7f344c32f042 in nvmf_vfio_user_poll_group_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5674
    #7 0x7f344c2c77f9 in nvmf_transport_poll_group_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/transport.c:582
    #8 0x7f344c2a06f6 in nvmf_poll_group_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/nvmf.c:71
    #9 0x7f344baf9c33 in thread_execute_poller /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:932
    #10 0x7f344bafb9b9 in thread_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:1058
    #11 0x7f344bafbd8f in spdk_thread_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:1109
    #12 0x7f344be5d9e2 in _reactor_run /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:903
    #13 0x7f344be5e032 in reactor_run /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:941
    #14 0x7f344be5eaa7 in spdk_reactors_start /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:1053
    #15 0x7f344be536b0 in spdk_app_start /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/app.c:753
    #16 0x4025d0 in main /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/app/nvmf_tgt/nvmf_main.c:47
    #17 0x7f344b304eaf in __libc_start_call_main (/usr/lib64/libc.so.6+0x3feaf)
    #18 0x7f344b304f5f in __libc_start_main_alias_1 (/usr/lib64/libc.so.6+0x3ff5f)
    #19 0x4022a4 in _start (/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/build/bin/nvmf_tgt+0x4022a4)
```

## Steps to Reproduce

1. Run vfio fuzzer test

## Context (Environment including OS version, SPDK version, etc.)
Fedora 35 6.0.9-100.fc35.x86_64
gcc version 11.3.1 20220421 (Red Hat 11.3.1-3) (GCC) 
Tested on physical system with E810 NIC

SPDK 726cddb1f

**Comment by karlatec** [comment]
FYI @sberbz

**Comment by changpe1** [comment]
change `uint32_t numdw` to `uint64_t numdw` should fix this issue.

**Comment by sberbz** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/16180

**Comment by karlatec** [comment]
Doesn't seem to fix the issue: https://ci.spdk.io/public_build/autotest-per-patch_94297.html

**Comment by sberbz** [comment]
I add casting to uint64_t and it seems to work fine now, please take a look at: 
https://ci.spdk.io/public_build/autotest-per-patch_94315.html

**Comment by jimharris** [comment]
> I add casting to uint64_t and it seems to work fine now, please take a look at:
> https://ci.spdk.io/public_build/autotest-per-patch_94315.html

I think just casting to uint32_t should be sufficient, we shouldn't need the uint64_t here.

**Comment by sberbz** [comment]
Thanks for notice, changed to uint32_t and rerun tests: 
https://spdkci.intel.com/job/autotest-per-patch/94399/

**Comment by tomzawadzki** [comment]
Patch fixing this issue has been merged https://github.com/spdk/spdk/commit/f80009632f2b781632352db9326cd2490b7c37f2, the issue can be closed.
