### ISSUE TITLE
Memory leak in calloc / libmlx5.so during NVMe-oF RDMA tests

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3016]
# Sighting report

libasan detects:
```
00:06:47.482  =================================================================
00:06:47.482  ==441348==ERROR: LeakSanitizer: detected memory leaks
00:06:47.482  
00:06:47.482  Direct leak of 592 byte(s) in 1 object(s) allocated from:
00:06:47.482      #0 0x7f86222e8097 in calloc (/usr/lib64/libasan.so.8+0xba097)
00:06:47.482      #1 0x7f861e8778a2 in create_cq (/usr/lib64/libmlx5.so.1+0x518a2)
00:06:47.482  
00:06:47.482  SUMMARY: AddressSanitizer: 592 byte(s) leaked in 1 allocation(s).
00:06:47.482    08:23:18	-- target/nvmf_example.sh@60 -- # trap - ERR
```
https://ci.spdk.io/public_build/autotest-per-patch_103661.html
https://ci.spdk.io/results/autotest-per-patch/builds/103661/archive/nvmf-phy-autotest/index.html
https://ci.spdk.io/results/autotest-per-patch/builds/103661/archive/nvmf-phy-autotest/build.log

during NVMe-oF RDMA test:
```
00:06:29.606  ************************************
00:06:29.606  START TEST nvmf_example
00:06:29.606  ************************************
00:06:29.606   08:23:02	-- common/autotest_common.sh@958 -- # xtrace_enable
00:06:29.606   08:23:02	-- common/autotest_common.sh@959 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/nvmf_example.sh --transport=rdma
```

Basically the test build fails at first RDMA functional test - nvmf_example.
This is weird because a few weeks ago I reported:
https://github.com/spdk/spdk/issues/2995
https://github.com/spdk/spdk/issues/2948
Both of these failures occured much later during tests and the tests were executed on the same OS image and kernel version as the one I'm currently reporting (6.1.14-200.fc37.x86_64).
The only thing changed since then which I recall are FW versions of Mellanox NICs. We updated to latest available FW version for all Mellanox NICs in the CI to deal with: https://github.com/spdk/spdk/issues/2965.

## Current Behavior

^up

## Possible Solution

Suppress libmlx5.so in asan_suppression_file?

## Steps to Reproduce

1. 
```
./configure --enable-asan --enable-ubsan --enable-coverage \
--enable-werror --enable-debug --with-crypto --with-fuse \
--with-idxd --with-nvme-cuse --with-rdma --with-usdt --with-fio \
--with-iscsi-initiator --with-nvme-cuse --with-vbdev-compress \
--with-dpdk-compressdev --with-rbd --with-ublk --with-raid5f \
--with-vfio-user --with-sma --with-xnvme --with-avahi --with-uring;
make -j
```

2.
```
SPDK_TEST_NVMF_NICS=mlx5 SPDK_TEST_NVMF=1 NET_TYPE=phy sudo -E test/nvmf/target/nvmf_example.sh --transport=rdma --iso
```

## Context (Environment including OS version, SPDK version, etc.)

Testing with https://review.spdk.io/gerrit/c/spdk/spdk/+/17143 based on SPDK 6db68e37371ca009fea0d5d9f7bf1b0bbb6b4f90
Fedora 37 `Linux spdk-WFP-05 6.1.14-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Feb 26 00:13:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by karlatec** [comment]
I installed `sudo dnf debuginfo-install libibverbs` in the system and ran tests manually in hope of getting more information from ASAN's error message, but no luck. It's still pretty vague.

**Comment by karlatec** [comment]
@AlekseyMarchuk can you take a look? Meanwhile I will spam the CI to run this across different nodes and see if I can hit some HW/FW combination where this issue does not reproduce.

**Comment by AlekseyMarchuk** [comment]
Hi @karlatec sure I'll take a look. It seems I know what is the root cause

**Comment by AlekseyMarchuk** [comment]
Hi @karlatec 
This patch should fix the issue, could you verify it?
https://review.spdk.io/gerrit/c/spdk/spdk/+/18287

**Comment by karlatec** [comment]
@AlekseyMarchuk I've rebased https://review.spdk.io/gerrit/c/spdk/spdk/+/17143/57 on top of your patch.
`nvmf-phy-autotest` (RDMA) still fails, but at a later stage and because of different issue. +1'd your fix.

https://ci.spdk.io/public_build/autotest-per-patch_104992.html
https://ci.spdk.io/results/autotest-per-patch/builds/104992/archive/nvmf-phy-autotest/build.log
