### ISSUE TITLE
[nvmf_delete_subsystem] member access within null pointer of type 'struct ibv_send_wr'

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#3129]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/109188/archive/nvmf-phy-autotest_50819/build.log
## Execution failed at
```
00:10:30.241  [2023-09-07 18:13:24.415786] subsystem.c:1209:spdk_nvmf_subsystem_listener_allowed: *WARNING*: Allowing connection to discovery subsystem on RDMA/192.168.100.8/4420, even though this listener was not added to the discovery subsystem.  This behavior is deprecated and will be removed in a future release.
00:10:32.152   18:13:26	-- target/delete_subsystem.sh@32 -- # rpc_cmd nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
00:10:32.152   18:13:26	-- common/autotest_common.sh@561 -- # xtrace_disable
00:10:32.152   18:13:26	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:10:32.152   18:13:26	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:10:32.152   18:13:26	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:10:32.152   18:13:26	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:10:32.152   18:13:26	-- common/autotest_common.sh@25 -- # set +x
00:10:32.413  rdma.c:638:14: runtime error: member access within null pointer of type 'struct ibv_send_wr'
00:10:32.413      #0 0x7f15620f9756 in _nvmf_rdma_request_free_data /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/rdma.c:638
00:10:32.413      #1 0x7f15620f9e9f in nvmf_rdma_request_free_data /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/rdma.c:666
00:10:32.413      #2 0x7f156210eae3 in _nvmf_rdma_request_free /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/rdma.c:1959
00:10:32.413      #3 0x7f15621181f2 in nvmf_rdma_request_process /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/rdma.c:2370
00:10:32.413      #4 0x7f15621247e4 in nvmf_rdma_qpair_process_pending /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/rdma.c:3299
00:10:32.413      #5 0x7f15621346db in nvmf_rdma_poller_poll /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/rdma.c:4670
00:10:32.413      #6 0x7f1562135169 in nvmf_rdma_poll_group_poll /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/rdma.c:4752
00:10:32.413      #7 0x7f1562097adb in nvmf_transport_poll_group_poll /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/transport.c:715
00:10:32.413      #8 0x7f1562054203 in nvmf_poll_group_poll /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/nvmf/nvmf.c:70
00:10:32.413      #9 0x7f1561730cfb in thread_execute_poller /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/thread/thread.c:946
00:10:32.413      #10 0x7f1561732a81 in thread_poll /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/thread/thread.c:1072
00:10:32.413      #11 0x7f1561733688 in spdk_thread_poll /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/thread/thread.c:1156
00:10:32.413      #12 0x7f1561b6619a in _reactor_run /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/event/reactor.c:914
00:10:32.413      #13 0x7f1561b667ea in reactor_run /var/jenkins/workspace/nvmf-phy-autotest/spdk/lib/event/reactor.c:952
00:10:32.413      #14 0x7f1561474a03 in eal_thread_loop ../lib/eal/common/eal_common_thread.c:210
00:10:32.413      #15 0x7f156148dd5e in eal_worker_thread_loop ../lib/eal/linux/eal.c:915
00:10:32.413      #16 0x7f1560f6512c in start_thread (/usr/lib64/libc.so.6+0x8b12c)
00:10:32.413      #17 0x7f1560fe6bbf in __clone3 (/usr/lib64/libc.so.6+0x10cbbf)
00:10:32.413  
00:10:37.696  Connection closed with partial response:
00:10:37.696  
00:10:37.696  
00:10:37.696   18:13:31	-- common/autotest_common.sh@588 -- # xtrace_enable
00:10:37.696   18:13:31	-- common/autotest_common.sh@589 -- # [[ 1 == 0 ]]
00:10:37.696    18:13:31	-- common/autotest_common.sh@589 -- # trap - ERR
00:10:37.696    18:13:31	-- common/autotest_common.sh@589 -- # print_backtrace
00:10:37.696    18:13:31	-- common/autotest_common.sh@1125 -- # [[ ehxBET =~ e ]]
00:10:37.696    18:13:31	-- common/autotest_common.sh@1127 -- # args=('nqn.2016-06.io.spdk:cnode1' 'nvmf_delete_subsystem' '--transport=rdma')
00:10:37.696    18:13:31	-- common/autotest_common.sh@1127 -- # local args
00:10:37.696    18:13:31	-- common/autotest_common.sh@1129 -- # xtrace_disable
00:10:37.696    18:13:31	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:10:37.696    18:13:31	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:10:37.696    18:13:31	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:10:37.696    18:13:31	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:10:37.696    18:13:31	-- common/autotest_common.sh@25 -- # set +x
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_109188.html

**Comment by AlekseyMarchuk** [comment]
I'll take it before release

**Comment by AlekseyMarchuk** [comment]
I found out that the issue should already be fixed in https://github.com/spdk/spdk/commit/ca59dd5d35d2664c475416999ff5a2f930f50e49
@mmkayPL please rebase your series to get the fix
Let's keep this issue open for a while, other people may hit the same problem

**Comment by mikeBashStuff** [comment]
Just to note that this issue still affects nightly builds under cvl, e.g.: https://ci.spdk.io/results/autotest-nightly/builds/2723/archive/nvmf-cvl-phy-autotest_561/index.html (last build is from master which already should include the ca59dd5)

**Comment by ksztyber** [comment]
Hey @AlekseyMarchuk, I've looked at this issue, since we have a 100% reproduction in our lab and I think there's still something wrong with the way we handle `transfer_wr`. I've pushed a patch [1] that should fix it (and the CI confirms it), could you take a look please?

[1] https://review.spdk.io/gerrit/c/spdk/spdk/+/19928

**Comment by AlekseyMarchuk** [comment]
Thanks @ksztyber for your fix. I missed that part
