### ISSUE TITLE
Nvme CQ processing routine assert with error message:SPDK_ERRLOG("cpl does not map to outstanding cmd\n");

### ISSUE THREAD

**Issue by baggio1008** [spdk/spdk#3243]
# Sighting report
I am encountering an issue during spdk based IO test. Spdk reports SPDK_ERRLOG("cpl does not map to outstanding cmd\n"); Below are the debug info I can share:
From the  PCIe TRACE, no duplicated CID CQEs are replied.
From the  PCIe TRACE, no duplicated CID SQEs are sent. Both host/device have no problem
Outstanding REQ count is smaller than IOQ size and only one SQ/CQ is used
Only one thread is running, no CPU race condition
SSD is from a start up which is not mainstream. While based on the PCIe trace, nothing wrong with both host and device
The issue can be reproduced on 2 different platforms. One is intel server with CPU Intel(R) Xeon(R) Platinum 8457C Debian 10 kernel:4.19.0-26-amd64.  another one is intel PC with CPU 12th Gen Intel(R) Core(TM) i7-12700K.  kernel 5.10.135.bsk.business.2-1-gd6e85c84dcce-amd64, debian 10
SPDK layer has no local change, we are just using NVMe layer API
SPDK version is the latest version. (commit 6e1f66fdb31a58d836c17aec9164b359cbfce62c (HEAD -> master, origin/master, origin/HEAD)
Author: Michal Berger <[michal.berger@intel.com](mailto:michal.berger@intel.com)>)
It looks like a memory/cache coherency issue for me. Next CQE is processed while it is not ready while next_phase tag check is true.
memory barrier is added while it does not help at all.
Thanks for any suggestion and comment about my issue.
I also implement a work-around to busy wait for phase tag becomes valid before processing the new CPL and it works. I add a counter in the busy wait loop, the counter is printed when it is not 0. the counter is 2 to 16. the issue will be triggered at around 1 out of 100k IO (edited)

## Expected Behavior
No error message should show during normal IO processing

## Current Behavior
SPDK_ERRLOG("cpl does not map to outstanding cmd\n") is shown.

Next_is_valid is true while current CPL phase tag is not expected, cid is with old value.

## Possible Solution

Currently I have 2 workaround which can fix the issue:
1. change local variable next_is_valid from variable on stack to static value in memory.
>>>	static bool			 next_is_valid = false;
<<<            bool	                  next_is_valid = false;
2. spin wait for cur_phase_tag == expect_phase_tag or simply ignore next_is_valid:
>>>	if (cpl->status.p != pqpair->flags.phase) {
<<<	if (!next_is_valid && cpl.status.p != pqpair->flags.phase) {

## Steps to Reproduce
It happens in our self developed software with spdk library integrated. It is a single thread application with both NVMe/ZNS SSD supported.
I reproduced the issue on both a small start up's ZNS SSD and Intel P5520 NVMe SSD 

## Context (Environment including OS version, SPDK version, etc.)

I tried both Intel P5520 Gen4 and one SSD Gen5 from a start up which is not mainstream. While based on the PCIe trace, nothing wrong with both host and device
The issue can be reproduced on 2 different platforms. One is intel server with CPU Intel(R) Xeon(R) Platinum 8457C Debian 10 kernel:4.19.0-26-amd64.  another one is intel PC with CPU 12th Gen Intel(R) Core(TM) i7-12700K.  kernel 5.10.135.bsk.business.2-1-gd6e85c84dcce-amd64, debian 10
SPDK layer has no local change, we are just using NVMe layer API
SPDK version is the latest version. (commit 6e1f66fdb31a58d836c17aec9164b359cbfce62c (HEAD -> master, origin/master, origin/HEAD)
Author: Michal Berger <[michal.berger@intel.com](mailto:michal.berger@intel.com)>)

**Comment by tomzawadzki** [comment]
[Bug scrub] From Slack - patch https://review.spdk.io/gerrit/c/spdk/spdk/+/21552 does not seem to address this issue in particular.

@benlwalker will leave a note on what kind of reproduction steps would be useful.

**Comment by Notherthing** [comment]
Hello. Is this bug fixed now? We also meet this bug  on v22.09. Does higher version SPDK meet this bug?

**Comment by baggio1008** [comment]
> Hello. Is this bug fixed now? We also meet this bug on v22.09. Does higher version SPDK meet this bug?

it is not fixed. please provide your hw/sw configuration. it might be only reproduced by using specific hw platform. I fixed it in my local platform and it works for me. please also try to use work around a provided above to see whether it can fix your problem

**Comment by Notherthing** [comment]
> > Hello. Is this bug fixed now? We also meet this bug on v22.09. Does higher version SPDK meet this bug?
> 
> it is not fixed. please provide your hw/sw configuration. it might be only reproduced by using specific hw platform. I fixed it in my local platform and it works for me. please also try to use work around a provided above to see whether it can fix your problem

Thanks so much, my friend. My machine is P5800x and an Intel Xeon Gold. I have already used your method, both (change local variable next_is_valid from variable on stack to static value in memory, and simply ignore next_is_valid) just now, and it seems fine. I have not check whether the results of my codes are right, but the error message no longer appears indeed. Thank you for your methods and your answers again, sincerely.
