### ISSUE TITLE
Not all UT are being executed w/Jenkins per patch testing

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#660]
Karol has the details, the SPDK_TEST_* flags are not being set for several modules (crypto for example) so unless the developer is actually doing this before they submit it would be very easy to introduce a UT issue on master (as is the case w/crypto right now).

**Comment by karlatec** [comment]
Config modified. All SPDK_TEST_* flags for unittest job should now default to 1.
@peluse Can you look it up and confirm this is OK for you?

**Comment by jimharris** [comment]
@karlatec - can you double check this?  I just looked at the unit test log for a couple of recent builds, and crypto still seems disabled.

**Comment by karlatec** [comment]
Hi Jim,
I enabled it just before adding the last comment here, but Seth had to later revert my changes to the config because one of the crypto unit tests was failing on ASAN on each build. 
Was this fixed and is it safe to turn on all UTs?

**Comment by jimharris** [comment]
Ah - thanks for reminding me.  This should be OK to turn back on now - we merged the patches from @peluse last week.  But maybe we should hold off until Monday so we don't run into any unexpected surprises right before the weekend.

**Comment by karlatec** [comment]
Just enabled all UTs for unittest_autotest job.
There's still a problem with blockdev UT's, ASAN fails on one of the tests.
```
13:01:37 =================================================================
13:01:37 ==1177581==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x0000008d411d bp 0x7fa89acc2450 sp 0x7fa89acc2368 T3)
13:01:37 ==1177581==The signal is caused by a READ memory access.
13:01:37 ==1177581==Hint: address points to the zero page.
```

For more info see autotest-per-patch builds 23858, 23859, 23860

**Comment by jimharris** [comment]
Thanks @karlatec.  Looks like an ASAN issue in the crypto bdev module.  Assigning to @peluse.

Here's a link:

http://10.102.17.206/results/autotest-per-patch/builds/23858/archive/unittest_autotests/build.log

**Comment by peluse** [comment]
on it...

**Comment by peluse** [comment]
hmmm, I don't get this w/ASAN on master.  Will investigate more

**Comment by peluse** [comment]
this isn't a UT failure, that's why it passed for me :) The failure happens running bdevio... should be able to repro locally now

**Comment by peluse** [comment]
having many challenges reproducing locally but getting closer.... @karlatec why is the unit_test Jenkins job running stuff other than unittests?

**Comment by karlatec** [comment]
It's not, or at least it shouldn't. The failing test which I mentioned is a result of changing config to:
SPDK_TEST_RUN_FUNCTIONAL_TEST=0
SPDK_TEST_UNITTEST=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
and leaving all other SPDK_TEST_* option undefined (which should default them to 1).

The result should be that this job would only run Unit Tests for all components/features, but no functional tests.

**Comment by karlatec** [comment]
Hi Paul, changed job configuration to:
```
SPDK_BUILD_DOC=1
SPDK_BUILD_IOAT_KMOD=0
SPDK_FEDORA_PACKAGING=0
SPDK_RUN_CHECK_FORMAT=1
SPDK_RUN_SCANBUILD=1
SPDK_RUN_VALGRIND=1
SPDK_RUN_FUNCTIONAL_TEST=0
SPDK_TEST_UNITTEST=1
SPDK_TEST_FTL=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
```
Looking at logs I think REDUCE tests are missing, even thoug I see that option SPDK_TEST_REDUCE is set to 1:
```
10:59:02   10:59:02	$ export SPDK_TEST_REDUCE
10:59:02   10:59:02	$ : 1
```

**Comment by karlatec** [comment]
Hi @peluse, can you confirm the change as OK so we can close the issue?

**Comment by darsto** [comment]
Bug scrub: There is an issue with ISA-L and RBD enabled at the same time.

@ZiyeYang have you pushed any patch to fix rbd and isa-l collision?

**Comment by karlatec** [comment]
So I've just changed SPDK_TEST_RBD to 0 for unit tests job, and it finished succesfully. 

I can see "with-reduce" in /configure options, but I still don't see reduce tests being run:
```
16:30:04 + grep -q '#define SPDK_CONFIG_REDUCE 1' /var/jenkins/workspace/Other/unittest_autotests/spdk/config.h
16:30:04 grep: /var/jenkins/workspace/Other/unittest_autotests/spdk/config.h: No such file or directory
```
I cannot find "test/unit/lib/reduce" anywhere in the logs.

**Comment by darsto** [comment]
All unit test are now running through our CI.
