### ISSUE TITLE
NVMf initiator crashes when bdev is used with vhost

### ISSUE THREAD

**Issue by nedved1** [spdk/spdk#664]
## Expected Behavior
Run fio test without any issues.

## Current Behavior
On VM, fio outputs errors:

```
randwrite: (g=0): rw=randwrite, bs=4K-4K/512K-512K/512K-512K, ioengine=libaio, iodepth=128
fio-2.2.10
Starting 1 thread
fio: io_u error on file /dev/sdb: Input/output error: write offset=28551151616, buflen=524288
fio: io_u error on file /dev/sdb: Input/output error: write offset=347373305856, buflen=524288
fio: io_u error on file /dev/sdb: Input/output error: write offset=137712107520, buflen=524288
fio: pid=1344, err=5/file:io_u.c:1582, func=io_u error, error=Input/output error

randwrite: (groupid=0, jobs=1): err= 5 (file:io_u.c:1582, func=io_u error, error=Input/output error): pid=1344: Wed Feb 13 10:05:21 2019
  write: io=64000KB, bw=48272B/s, iops=0, runt=1357618msec
    slat (usec): min=11, max=63, avg=16.40, stdev= 5.73
    clat (msec): min=125, max=1357.6K, avg=977422.01, stdev=611891.68
     lat (msec): min=125, max=1357.6K, avg=977422.03, stdev=611891.68
    clat percentiles (msec):
     |  1.00th=[  127],  5.00th=[  133], 10.00th=[  139], 20.00th=[  155],
     | 30.00th=[16712], 40.00th=[16712], 50.00th=[16712], 60.00th=[16712],
     | 70.00th=[16712], 80.00th=[16712], 90.00th=[16712], 95.00th=[16712],
     | 99.00th=[16712], 99.50th=[16712], 99.90th=[16712], 99.95th=[16712],
     | 99.99th=[16712]
    bw (KB  /s): min=   13, max=   13, per=27.66%, avg=13.00, stdev= 0.00
    lat (msec) : 250=21.60%, >=2000=76.54%
  cpu          : usr=0.01%, sys=0.00%, ctx=99, majf=0, minf=5
  IO depths    : 1=0.6%, 2=1.2%, 4=2.5%, 8=4.9%, 16=9.9%, 32=19.8%, >=64=61.1%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=97.3%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=2.7%
     issued    : total=r=34/w=128/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
  WRITE: io=64000KB, aggrb=47KB/s, minb=47KB/s, maxb=47KB/s, mint=1357618msec, maxt=1357618msec

Disk stats (read/write):
  sdb: ios=72/128, merge=0/0, ticks=584/30864, in_queue=31448, util=2.23%
```

On host:
vhost outputs errors and hangs:

```
nvme_rdma.c:1170:nvme_rdma_build_sgl_inline_request: *ERROR*: Unable to prepare request. Too many SGL elements
nvme_rdma.c:1519:nvme_rdma_qpair_submit_request: *ERROR*: nvme_rdma_req_init() failed
bdev_nvme.c:1682:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
nvme_rdma.c:1170:nvme_rdma_build_sgl_inline_request: *ERROR*: Unable to prepare request. Too many SGL elements
nvme_rdma.c:1519:nvme_rdma_qpair_submit_request: *ERROR*: nvme_rdma_req_init() failed
bdev_nvme.c:1682:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
nvme_rdma.c:1170:nvme_rdma_build_sgl_inline_request: *ERROR*: Unable to prepare request. Too many SGL elements
nvme_rdma.c:1519:nvme_rdma_qpair_submit_request: *ERROR*: nvme_rdma_req_init() failed
bdev_nvme.c:1682:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
nvme_rdma.c:1170:nvme_rdma_build_sgl_inline_request: *ERROR*: Unable to prepare request. Too many SGL elements
nvme_rdma.c:1519:nvme_rdma_qpair_submit_request: *ERROR*: nvme_rdma_req_init() failed
bdev_nvme.c:1682:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
nvme_rdma.c:1170:nvme_rdma_build_sgl_inline_request: *ERROR*: Unable to prepare request. Too many SGL elements
nvme_rdma.c:1519:nvme_rdma_qpair_submit_request: *ERROR*: nvme_rdma_req_init() failed
bdev_nvme.c:1682:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
```

## Steps to Reproduce
1. Run nvmf_tgt, configure nvmf subsystem and assign nvme device to that subsystem.

```
./spdk/app/nvmf_tgt/nvmf_tgt -s 512 -m 0xF -r /tmp/nvmf_rpc.sock --wait-for-rpc &
./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock start_subsystem_init
./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock nvmf_create_transport -t RDMA -u 8192 -p 4
./spdk/scripts/gen_nvme.sh --json | sudo ./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock load_subsystem_config
./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock nvmf_subsystem_create nqn.2018-02.io.spdk:cnode1 -a -s SPDK01
./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock nvmf_subsystem_add_ns nqn.2018-02.io.spdk:cnode1 Nvme0n1
./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock nvmf_subsystem_add_listener nqn.2018-02.io.spdk:cnode1 -t rdma -a 192.168.100.101 -s 4420
```

2. Run  vhost and create vhost controller with nvmf bdev.

```
./spdk/app/vhost/vhost -p 0 -s 1024 -r /tmp/rpc.sock -u &
./spdk/scripts/rpc.py -s /tmp/rpc.sock construct_nvme_bdev -b Nvme0 -t rdma -f ipv4 -a 192.168.100.101 -s 4420 -n nqn.2018-02.io.spdk:cnode1
./spdk/scripts/rpc.py -s /tmp/rpc.sock construct_vhost_scsi_controller naa.VhostScsi0.1
./spdk/scripts/rpc.py -s /tmp/rpc.sock add_vhost_scsi_lun naa.VhostScsi0.1 0 Nvme0n1
```

3. Start VM with attached vhost controller.

```
taskset -a -c 1 /usr/local/qemu/spdk-2.12/bin/qemu-system-x86_64 -snapshot -m 512 --enable-kvm -cpu host -smp 1 -vga std -vnc :101 -daemonize -object memory-backend-file,id=mem,size=512M,mem-path=/dev/hugepages,share=on,prealloc=yes,host-nodes=0,policy=bind -monitor telnet:127.0.0.1:10102,server,nowait -numa node,memdev=mem -net user,hostfwd=tcp::10100-:22,hostfwd=tcp::10101-:8765 -net nic -drive file=/home/sys_sgsw/vhost_vm_image.qcow2,if=none,id=os_disk -device ide-hd,drive=os_disk,bootindex=0 -chardev socket,id=char_VhostScsi0,path=/home/sys_sgci/naa.VhostScsi0.1 -device vhost-user-scsi-pci,id=scsi_VhostScsi0,num_queues=1,chardev=char_VhostScsi0
```

4.  Run fio on VM.

```
fio fio.job
```

```
fio.job:
[global]
blocksize=4k-512k
iodepth=128
ioengine=libaio
filename=/dev/sdb
group_reporting
thread
numjobs=1
direct=1
do_verify=1
verify=md5
verify_fatal=1
verify_dump=1
verify_backlog=8

[randwrite]
rw=randwrite
runtime=15
time_based
stonewall
```

## Context (Environment including OS version, SPDK version, etc.)
Host:

```
os: Fedora 28
kernel: 4.20.6-100.fc28.x86_64
NVMe: INTEL SSDPE2MD400G4
NIC: Mellanox MT27700 ConnectX®-4
SPDK v19.04-pre / DPDK 18.11.0
```

VM:

```
os: Ubuntu 16.04
kernel: 4.4.0
```

**Comment by darsto** [comment]
@pawelwod pointed out earlier that NVMf uses max i/o size of 128k by default. @nedved1 can you try increasing it to 512k?

**Comment by pawelwod** [comment]
> increasing it to 512k?

decrease to 4k-128k (or even 4k-64k) as 4k-512k is already used in failing test.

**Comment by nedved1** [comment]
@darsto @pawelwod After decreasing blocksize to 4k-128k, fio test completed successfully.

**Comment by optimistyzy** [comment]
"./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock nvmf_create_transport -t RDMA -u 8192 -p 4 "

Can you Remove -u 8192

**Comment by nedved1** [comment]
@optimistyzy fio hangs, vhost crashes, got message:
```vhost: nvme_rdma.c:1159: nvme_rdma_build_sgl_inline_request: Assertion `length <= remaining_payload' failed.```

**Comment by darsto** [comment]
The original error "too many SGL elements" seems to be caused by #640, which should be fixed now.

@nedved1 could you re-check on master?

**Comment by nedved1** [comment]
@darsto I've checked it on master, the issue can be still reproduced.

**Comment by Seth5141** [comment]
@nedved1 @darsto Sorry, just seeing this one for the first time. Any I/O larger than the transports max I/O size needs to be split to max I/O size before being processed by the NVMe-oF components. I will look at this a bit closer when I get into the office.

**Comment by Seth5141** [comment]
@nedved1 When you create the nvmf tgt, can you recreate the transport with the following options?

./spdk/scripts/rpc.py -s /tmp/nvmf_rpc.sock nvmf_create_transport -t RDMA -u 8192 -p 4 -i 524288 -u 32768
This increases the max io size in the target to 512K and increases the I/O unit size to 32K or 1/16th of the max I/O size. My thought is that will fix the immediate issue you are facing here. However, there is an underlying problem here with vhost and the nvme initiator not communicating the max_io_size with each other.

**Comment by nedved1** [comment]
@Seth5141 I've tried creating transport with 512k max i/o size and 32k i/o unit size but this issue remains.

**Comment by darsto** [comment]
@ZiyeYang could you take a look?

**Comment by Seth5141** [comment]
@nedved1 So it looks like this is caused by an assumption in the nvme-rdma code. In build_sgl_request, we assume that an IOV will not be longer than the request to which it belongs. (i.e. assert(length <= remaining_payload)). It seems that other levels of the stack don't make this assumption. For example in nvme_ns_cmd.c when we examine a new sgl element in _nvme_ns_cmd_split_request_sgl, we do the following check:

if (req_current_length + sge_length > req->payload_size) {
	sge_length = req->payload_size - req_current_length;
}.

I am not a huge fan of allowing SGL element lengths to exceed that of the request, but it appears that this is the common way of handling them in the bdev layer. If you go back to the master on which you tested this and replace the assert with a check similar to the one found in nvme_ns_cmd, the issue goes away.

Unfortunately, I recently made some changes to the way we handle splitting large I/O when our initiator is communicating with our target, and I appear to have re-broken this functionality on master. I am going to figure out what has gone wrong and push a few patches that should fix this issue and the new ones that have arisen on master.

**Comment by Seth5141** [comment]
@nedved1 Sorry to take so long on this one. It should all be fixed here. https://review.gerrithub.io/c/spdk/spdk/+/450873. Please try again on your system using the tip of this change series. If it is fixed on your system, please clsoe the issue.
Thanks!

**Comment by nedved1** [comment]
@Seth5141 Great job!  It seems that your patches fix this issue.

**Comment by Seth5141** [comment]
Thanks!
