### ISSUE TITLE
SPDK fails to come up after long FIO run - Assertion `page->id == blob->id' failed

### ISSUE THREAD

**Issue by dacrespi** [spdk/spdk#691]
I'm running a 3 ssd RAID 0 stripe at a stripe size of 64K. These are 4TB Samsung SSD's. I'm running this RAID group as a mounted drive on my client box, driving traffic using FIO at a -bs 16K. There didn't appear to be any problem with the run (4 hrs). I shut down the target for the evening, and started it up this morning, it crashed with "nvmf_tgt: blobstore.c:572: _spdk_blob_parse: Assertion `page->id == blob->id' failed"

Using the blobcli, it produces this same error ("blobcli: blobstore.c:571: _spdk_blob_parse: Assertion `page->id == blob->id' failed".) when looking at each individual drive of the RAID set. I'm not that familiar with how the blobs are laid out, the the ssd's used in the RAID set produces a HUGE file when doing the dump. Another drive that also was tested as a single has a pretty small file.  I've included the dump files in the attached zip file.

Nvme3n1 is the single drive
Nvme5n1,6 & 7 is RAID stripe.
[Nvme.zip](https://github.com/spdk/spdk/files/2901424/Nvme.zip)

## Expected Behavior
The FIO run shouldn't have any effect on SPDK running or the raid stripe, and SPDK should be able to not crash after restarting with these three ssd's plugged in.

## Current Behavior
After the FIO run, everything looks to be okay.  I ran multiple FIO runs with these drives without issue.
SPDK was shutdown for the evening.  The next morning when starting up SPDK, it crashed with "nvmf_tgt: blobstore.c:572: _spdk_blob_parse: Assertion `page->id == blob->id' failed"

## Possible Solution
The only thing that has worked for me so far is to re-initialize the blobs on each of the three ssd's.
Not a viable solution.

## Steps to Reproduce
1. Create three LVOL Stores
 "construct_lvol_store HotInNvme1n1 Corp_1"
 "construct_lvol_store HotInNvme3n1 Corp_3"
 "construct_lvol_store HotInNvme4n1 Corp_4"

2. Create three LVOLs used for the raid stripe.
"construct_lvol_bdev -t raidVol_17 819200 -l Corp_3"
"construct_lvol_bdev -t raidVol_24 819200 -l Corp_4"
"construct_lvol_bdev -t raidVol_32 819200 -l Corp_1"

3. Build the raid0 stripe
"construct_raid_bdev -r 0 -z 64 -b "Corp_3/raidVol_17 Corp_4/raidVol_24 Corp_1/raidVol_32" -n RAID0_7"

4. Add to the subsystem (running RoCEv2 RDMA via Mellanox 100Gb rNIC)
"nvmf_subsystem_add_ns nqn.2018-12.io.spdk:cntlr9 RAID0_7"

5. On a client system, connect the namespace
 "nvme connect -t rdma -a 192.168.2.100 -n nqn.2018-12.io.spdk:cntlr9"

6. Make filesystem on added drive
"mkfs -t ext4 /dev/nvme1n1"

7. Mount drive
"mount /dev/nvme1n1 /media/disk1"

8. Run FIO
      fio --bs=16K \
            --numjobs=16 \
            --iodepth=16 \
            --loops=1 \
            --ioengine=libaio \
            --direct=1 \
            --invalidate=1 \
            --fsync_on_close=1 \
            --randrepeat=1 \
            --norandommap \
            --time_based \
            --runtime=240M \
            --filename=/media/disk1/TEST/file.txt \
            --name=read-phase \
            --allow_mounted_write=1 \
            --size=400G \
            --rw=randread  &

9. Shutdown SPDK

10. Restart SPDK

## Context (Environment including OS version, SPDK version, etc.)
SPDK version - v19.01-223-g954728e9d
Starting SPDK v19.04-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0xF0F0F0F0 -m 32768 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid1029 ]
EAL: Detected 32 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 624:spdk_app_start: *NOTICE*: Total cores available: 16
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 12
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 13
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 14
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 20
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 15
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 23
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 28
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 21
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 29
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 31
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 30
reactor.c: 233:_spdk_reactor_run: *NOTICE*: Reactor started on core 22

Client OS:
    18.04 Ubuntu 
    Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Target OS:
    18.04 Ubuntu  
    Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

SSD's are Samsung 4TB

**Comment by dacrespi** [comment]
I just noticed that it appears that running the blobcli produced a core dump for the ssd in question.
[core.zip](https://github.com/spdk/spdk/files/2902599/core.zip)

**Comment by darsto** [comment]
Bug scrub: This should be easily reproducible.

**Comment by dacrespi** [comment]
I ran an additional experiment yesterday.  I used the same three ssd's, but did not put them into a raid bdev.  I did the same steps on the client and ran the same fio settings.  This morning when booting up the target, one of the three drives was corrupted, the other two were fine.  I've attached the blobcli output of that drive before and after the fio run, along with the core dump of running the command.  The log file also shows its hitting the same assert.

[fio_fail.zip](https://github.com/spdk/spdk/files/2906646/fio_fail.zip)

**Comment by dacrespi** [comment]
Additional info - I just noticed that the other two drives used in the test have lost their LV blob's.  There isn't any record of it when listing out the blobs of the devices.  I noticed these were missing after adding the ssd's back into spdk.  Each reported the correct LVOL, but not the LV.

**Comment by pelplinski** [comment]
Hi Dacrespi,
First thing I noticed is that blobstore is not shut down cleanly (look at the blobcli output, line Clean: 0).
How do you shutdown spdk? Does any errors occur? Could you provide logs?

However, even if spdk is killed, metadata should not get corrupted, so I have to reproduce this and debug.

**Comment by dacrespi** [comment]
Hi Piotr,

It’s running in a container, so docker brings it down with the system shutting down.
Is there a “proper” way of shutting it down?  I’ve looked in the documentation and didn’t see anything
specific for that.

And I agree with your comment. “…metadata should not get corrupted…”!

I ran another set of experiments yesterday on raw devices.  The same thing happened.  I was thinking it could
be an interaction with ext4.  Not having the filesystem will make it a bit easier to figure out.  Of the 4 ssd’s I
used in yesterdays experiment, one was unreadable (nothing except an assert from blobcli), the other 3 all
lost their lvol’s, but the lvol store was okay.  Definitely seems to be time related.  I did a bunch of short runs
yesterday and everything was fine.  I even did a few short tests using IOmeter, all was good.  When the
period exceeds a few hours (I had 240 minutes in the runs), things go bad.  The devices are okay to use as
long as SPDK isn’t restarted… including creating new LV’s.  I guess when SPDK starts is when it has to make
sense of what’s on the devices?  Are there any checks of the blob/blob stores during normal operation?  Like
background health checks etc?

I don’t have any detail logs to provide, other than the stuff I’ve already posted.  I’m going to do another
test today and I’ll turn on some of the logging.  Do you have any suggestions of what would provide the
best output for you?

Thanks for looking into this so quickly, and any other tests or data you need, just let me know!

Regards,

           David

**Comment by pelplinski** [comment]
I tried to replicate it locally on smaller thin provisioned lvols, but with no success. I think it might be related to NVMf.
Did you ever encored a situation, where lvolstore is not shutdown cleanly (Clean: 0), but there are visible lvols on it? If so, could you try verify payload of a lvol? You can dump blob to a file using blobcli -d.

**Comment by darsto** [comment]
Bug scrub: @pelplinski reproduced it and still needs to debug.

@benlwalker suggests to figure out the differences between NVMf and FIO (?) This might be related to zero-copy READ.

**Comment by peluse** [comment]
try adding instrumentation in code path to get a hint, document simplified steps to repro (ex not using RAID 0)

**Comment by pelplinski** [comment]
### Simplified steps to reproduce

**On server:**
1. Create lvolstore
construct_lvol_store Nvme0n1 Lvs0

2. Create thin provisioned lvols
construct_lvol_bdev -t Lvol0 819200 -l Lvs0
construct_lvol_bdev -t Lvol1 819200 -l Lvs0
construct_lvol_bdev -t Lvol2 819200 -l Lvs0

3. Add to the nvmf subsystem 
nvmf_subsystem_add_ns nqn.2018-12.io.spdk:cnode1 Lvol1

**On client:** 
4. Connect the namespace
nvme connect -t rdma -a 192.168.2.100 -n nqn.2018-12.io.spdk:cnode1

5. Run FIO 
sudo fio --bs=16K 
--numjobs=16 
--iodepth=16 
--loops=1 
--ioengine=libaio 
--direct=1 
--invalidate=1 
--fsync_on_close=1 
--randrepeat=1 
--norandommap 
--time_based 
--runtime=240M 
--filename=/dev/nvme1n1
--name=read-phase 
--allow_mounted_write=1 
--size=400G 
--rw=randread

On client:
6. Shutdown SPDK
7. Restart SPDK
8. Hit the assert on:
construct_lvol_store Nvme0n1 Lvs0

**Comment by jimharris** [comment]
Hi @pelplinski,

Can you confirm a few things:

1) Three lvols are created, but only one is used.  Do we know that you must create three lvols for this issue to happen?
2) I was really surprised to see that the fio job is reads only.  There are no writes needed at all to make this problem happen?
3) What percentage of the time does this issue occur when running these set of steps?
4) Is it possible to reproduce it at a shorter time length - maybe 10, 30 or 60 minutes instead of 240?

Thanks,

-Jim

**Comment by darsto** [comment]
Bug scrub: prepare a very simple reproduction setup. narrow it down to a single lvol, try nvmf loopback. try iscsi instead of nvmf and see if it reproduces

**Comment by pelplinski** [comment]
It looks like issue is specific to NVMf. I cannot reproduce it either on any local backend or iSCSI.

**Comment by pelplinski** [comment]
I have run a couple more tests and I can confirm that I cannot see any metadata corruption on latest master. 
I did tried:
- Physical machine with NVMf
- 4h and 8h tests
- shutting down cleanly and killing spdk tgt
- Multiple and single thin provisioned lvol

**Comment by benlwalker** [comment]
Fixed by 795134891 and e740ba637.

**Comment by SavanAnjaria** [comment]
@benlwalker 
Looks like the issue still persists as I am hitting the same assert with another scenario.
1. Create NVMe Bdev and LVS on top of that
2. Create 8 thin provisioned lvols of 3GB size each
3. Create NVMf subsystem and connect that with an initiator
4. Discover and connect NVMe Controller on the initiator side which will then list all the 8 lvols on the initiator side
5. Run fio writes for some time (~5 minutes) on all the lvols
6. Stop the IOs, disconnect the controller on the initiator side
7. Destroy NVMf subsystem on the target side
8. Issue destroy_lvol_bdev on the first thin provisioned lvol.
9. I am hitting this issue.

Here is the BT of this assertion:

#0  0x00007fe215629207 in raise () from /lib64/libc.so.6
#1  0x00007fe21562a8f8 in abort () from /lib64/libc.so.6
#2  0x00007fe215622026 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fe2156220d2 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000041387c in _spdk_blob_parse (pages=0x200008602000, page_count=9,
    blob=0x1c4ebe0) at blobstore.c:586
#5  0x00000000004146b4 in _spdk_blob_load_cpl (seq=0x1dd1b30, cb_arg=0x20c1460, bserrno=0)
    at blobstore.c:1000
#6  0x000000000041fdce in spdk_bs_sequence_completion (channel=0x1c503d0, cb_arg=0x1dd1b30,
    bserrno=0) at request.c:99
#7  0x000000000042180c in bdev_blob_io_complete (bdev_io=0x20000887a780, success=true,
    arg=0x1dd1b60) at blob_bdev.c:86
#8  0x00000000004bfd49 in _spdk_bdev_io_complete (ctx=0x20000887a780) at bdev.c:3453
#9  0x00000000004c00e1 in spdk_bdev_io_complete (bdev_io=0x20000887a780,
    status=SPDK_BDEV_IO_STATUS_SUCCESS) at bdev.c:3540
#10 0x00000000004c0389 in spdk_bdev_io_complete_nvme_status (bdev_io=0x20000887a780, sct=0,
    sc=0) at bdev.c:3605
#11 0x000000000042ca43 in bdev_nvme_readv_done (ref=0x20000887aac0, cpl=0x200016a00340)
    at bdev_nvme.c:1696
#12 0x000000000043ee74 in nvme_complete_request (cb_fn=0x42c87a <bdev_nvme_readv_done>,
    cb_arg=0x20000887aac0, req=0x200015a62940, cpl=0x200016a00340) at nvme_internal.h:949
#13 0x0000000000441ae4 in nvme_pcie_qpair_complete_tracker (qpair=0x200015a7fa18,
    tr=0x2000084cb000, cpl=0x200016a00340, print_on_error=true) at nvme_pcie.c:1315
#14 0x000000000044369b in nvme_pcie_qpair_process_completions (qpair=0x200015a7fa18,
    max_completions=64) at nvme_pcie.c:2091
#15 0x0000000000448664 in nvme_transport_qpair_process_completions (qpair=0x200015a7fa18,
    max_completions=0) at nvme_transport.c:216
#16 0x0000000000444487 in spdk_nvme_qpair_process_completions (qpair=0x200015a7fa18,
    max_completions=0) at nvme_qpair.c:446
#17 0x0000000000428be3 in bdev_nvme_poll (arg=0x1c504d0) at bdev_nvme.c:187
#18 0x00000000004b0ed1 in spdk_thread_poll (thread=0x1c51720, max_msgs=0,
    now=17828362461664570) at thread.c:469
#19 0x00000000004ab097 in _spdk_reactor_run (arg=0x1c50f40) at reactor.c:271
#20 0x00000000004ab45a in spdk_reactors_start () at reactor.c:374
#21 0x00000000004a9c56 in spdk_app_start (opts=0x7fffa36d5770,
    start_fn=0x405d6f <nvmf_tgt_started>, arg1=0x0) at app.c:688
#22 0x0000000000405e75 in main (argc=5, argv=0x7fffa36d5908) at nvmf_main.c:75

**Comment by tomzawadzki** [comment]
@SavanAnjaria 
Hi I've been trying to reproduce with steps that you've provided, but have been unable to so far. Please see following script that tries to recreate it:
https://gist.github.com/tomzawadzki/cc25af80371b6d696eef9dff91b628de
Script assumes its possible to run it locally on same system. I've used Soft-RoCE on mine.

1) Does the script follow the methodology you've used to see the issue ? Does running it on your system reproduce it ?
2) From your steps, is 8 ("destroy_lvol_bdev on the first thin provisioned lvol") required for the issue to occur  ?
3) Let's try simplifying the scenario to see what are minimal set of operations for it to occur:
   - single lvol
   - is I/O for 5 minutes minimum for issue to occur
4) Eliminate/change of components used. I know that Piotr verified some, but since the test scenario was at different time - those might have changed as well.
   - switch NVMe-oF to iSCSI
   - switch NVMe-oF/fio to bdevperf
   - switch NVMe bdev to aio bdev

**I'll gladly help out with the points above, but help with reproducing it ( 1. ) would be greatly appreciated.**


Besides the above, in DM on Slack you've mentioned some pointers that I'll explore. Some things pointed out:
- There is CRC mismatch for one of the page index associated with the blob, as well as 'page->id == blob->id' issue
- the pointer to page array that we pass during serialize operation (while writing the blob metadata) belongs to another blob
- the serialization during cluster allocation looks fine, its the sync during unload that passes incorrect pointers
- the CRC mismatch occurs for pages further than page 0

I'll investigate points above and try to reproduce them as well.

**Comment by tomzawadzki** [comment]
Small update:
When creating script for this test, a CRC mismatch error occured for me. Unfortunetly it seems to be unrelated https://github.com/spdk/spdk/issues/869.

Still no reproduction. Just wanted to clear up some details.
1. Shutdown SPDK app in your case means SIGINT (ctrl+c), not a SIGKILL (-9) ?
2. When SPDK app is started again, configuration contains only the NVMe device (and no further RPC are issued at time of starting) ?

Minor updates to script:
<details><summary>Here</summary>
<p>

```bash
set -x

SPDK="/home/tzawadzk/spdk-current"
rpc="$SPDK/scripts/rpc.py"
bdf="0000:82:00.0"
ip="10.102.17.107"
nqn="nqn.2016-06.io.spdk:cnode1"

sudo nvme disconnect -n $nqn
sudo kill -9 $(pgrep -f nvmf_tgt -o)
sleep 3

cd $SPDK
cat > ./no_gpt.conf << EOL
[Gpt]
Disable No
EOL
sleep 3
$SPDK/app/nvmf_tgt/nvmf_tgt -c ./no_gpt.conf -L blob -L blob_rw -L lvol -L lvolrpc -L vbdev_lvol -L bdev &
nvmf_pid=$!
echo "NVMF_PID $nvmf_pid"
sleep 3

$rpc construct_nvme_bdev -b Nvme0 -t pcie -a $bdf
sleep 3
$rpc destroy_lvol_store -l Lvs0 #Destroy LVS from previous test run
sleep 3
$rpc construct_lvol_store Nvme0n1 Lvs0
sleep 3
$rpc construct_lvol_bdev -t Lvol0 3072 -l Lvs0
$rpc construct_lvol_bdev -t Lvol1 3072 -l Lvs0
$rpc construct_lvol_bdev -t Lvol2 3072 -l Lvs0
$rpc construct_lvol_bdev -t Lvol3 3072 -l Lvs0
$rpc construct_lvol_bdev -t Lvol4 3072 -l Lvs0
$rpc construct_lvol_bdev -t Lvol5 3072 -l Lvs0
$rpc construct_lvol_bdev -t Lvol6 3072 -l Lvs0
$rpc construct_lvol_bdev -t Lvol7 3072 -l Lvs0
sleep 5
echo "Lvols set up"

$rpc nvmf_create_transport -t RDMA -u 8192 -p 4 -c 0
$rpc nvmf_subsystem_create $nqn -a -s SPDK00000000000001 -d SPDK_Controller1
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol0
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol1
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol2
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol3
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol4
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol5
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol6
$rpc nvmf_subsystem_add_ns $nqn Lvs0/Lvol7
$rpc nvmf_subsystem_add_listener $nqn -t rdma -a $ip -s 4420
sleep 5
echo "NVMF CREATED"

sudo nvme connect -t rdma -a $ip -n $nqn
sleep 5
lsblk
sleep 5

sudo fio --bs=16K \
--numjobs=16 \
--iodepth=16 \
--ioengine=libaio \
--direct=1 \
--invalidate=1 \
--norandommap \
--time_based \
--runtime=5M \
--filename=/dev/nvme0n1 \
--filename=/dev/nvme0n2 \
--filename=/dev/nvme0n3 \
--filename=/dev/nvme0n4 \
--filename=/dev/nvme0n5 \
--filename=/dev/nvme0n6 \
--filename=/dev/nvme0n7 \
--filename=/dev/nvme0n8 \
--name=write \
--rw=randrw

sleep 5
sudo nvme disconnect -n $nqn
sleep 5

$rpc delete_nvmf_subsystem $nqn
$rpc destroy_lvol_bdev Lvs0/Lvol0
sleep 5

sudo kill -2 $nvmf_pid
sleep 5
echo "FIO run ended"

$SPDK/app/nvmf_tgt/nvmf_tgt -c ./no_gpt.conf -L blob -L blob_rw -L lvol -L lvolrpc -L vbdev_lvol -L bdev &
nvmf_pid=$!
echo "NVMF_PID $nvmf_pid"
sleep 3

$rpc construct_nvme_bdev -b Nvme0 -t pcie -a $bdf
sleep 3

$rpc get_bdevs
echo "Lvol store reloaded properly"
sudo kill -2 $nvmf_pid
sleep 5

```

</p>
</details>

**Comment by tomzawadzki** [comment]
I've tried to follow up on the tips around serialization of md, but via code inspection I couldn't find anything wrong with it.

@SavanAnjaria Please let me know if you get a chance to checkout and verify the script posted, or some of the proposed ways to narrow it down.

**Comment by SavanAnjaria** [comment]
@tomzawadzki : Looked at your script. Here are my replies to your questions:
1. Script follows the reproduction steps that I had followed except for the LVOL destruction at the end I believe. I haven't tried running that on my machine yet. I'll give a shot and update you.
2. I usually see this issue with destroy_lvol_bdev only
3. I can create minimal config to reproduce this issue.

Are you running this on SPDK tip code (with your changes w.r.t. blob metadata) or on SPDK released code? I guess it would be a good idea to check the behavior of this script on the tip of SPDK vs SPDK Release 19.04. I'll also take SPDK tip code and perform reproduction steps from my end.

**Comment by tomzawadzki** [comment]
Previous results, without reproduction, were on SPDK master. 
I've re-ran the script with SPDK 19.04.1, no reproduction as well.
Which SPDK version were you using ?

Can you please clarify 1. and 2. in previous comment ? You say that destroy_lvol_bdev only() is required, and the script does not follow the flow in that regard. Yet posted script deletes first lvol bdev right before restarting the application. Were you performing the deletion at some other point in time ?

**Comment by SavanAnjaria** [comment]
@tomzawadzki :
Missed the lvol destruction part from your script. It follows all the reproduction steps I had mentioned. I was able to reproduce this issue with 19.04.1 released version. By EOD, will post the result with SPDK Master tip code

**Comment by tomzawadzki** [comment]
@SavanAnjaria 
You did reproduce the issue on SPDK 19.04.1 with script exactly as posted ?
If that is the case, there has to be some difference between our setups. Lets try to narrow it down (here are mine):
- `uname -r ` 5.1.12-300.fc30.x86_64 Fedora 30
- Soft-RoCE (rxe_cfg) from https://github.com/SoftRoCE/librxe-dev.git Are you using Soft-RoCE ?
- `fio -v` fio-3.3
- NVMe `sudo ./examples/nvme/identify/identify | grep "Model Number:"`  INTEL SSDPEDMD400G4

If you are able to reproduce it on SPDK master as well, please let me know about the above on your system.
After we could proceed with trying to eliminate some of variables as outlined by my previous comment https://github.com/spdk/spdk/issues/691#issuecomment-513722663.

**Comment by SavanAnjaria** [comment]
@tomzawadzki : Not using the script. I meant to say that, using the exact steps I have mentioned in the reproduction (running IOs from the different server), I was able to reproduce this issue on 19.04.1 but, I am yet to take SPDK master and see the results.

**Comment by darsto** [comment]
Bug scrub: switching the priority to medium - we need a confirmation if this reproduces on master

**Comment by SavanAnjaria** [comment]
@tomzawadzki
Just to make a note of the points we discussed:
- The issue didn't reproduce for me on master with 3 attempts of the same reproduction steps.
- I am going to do an exercise to narrow down the commit(s) that's fixing/hiding/masking this issue.
- This issue plays hide and seek at times. So, while I would be doing above said exercise, if the issue reproduces on master as well, I'll report the same.
- I'll try to run the script provided by you on my code base where the issue reproduces most of the time and see if I can bridge some gap in reproducing this issue.

**Comment by tomzawadzki** [comment]
@SavanAnjaria 
Were you able to take some of the previously mentioned steps ?

When working on #906, I was able to produce the same assert. See log [here](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/39949/archive/nvmf_phy_autotest/build.log) from [patch](https://review.gerrithub.io/c/spdk/spdk/+/465075).
Steps in the patch are:
1) create two thin provisioned lvol bdevs with sizes larger than lvol store
2) expose through NVMe-oF
3) do 3 min I/O to first lvol, then 3 min to second lvol
4) assert is triggered on deletion of first lvol bdev

I will work from this script to narrow down the issue, but seems to reproduce each time on my machine as well.

**Comment by SavanAnjaria** [comment]
@tomzawadzki : That's a good news. I haven't been able to take up the previously mentioned steps as the server I have been using have gone for maintenance. But, I'll try to pick a working server soon and provide further update on this issue.

**Comment by jimharris** [comment]
Bug scrub: let's discuss in next Euro bug scrub with @tomzawadzki

**Comment by tomzawadzki** [comment]
In order to test the current state of this issue, ported the reproduction script to new CI/review board.
https://review.spdk.io/gerrit/c/spdk/spdk/+/1111
https://ci.spdk.io/results/autotest-per-patch/builds/5400/archive/nvmf-phy-autotest/build.log

It results in different asserts at the same time as previous tests (deletion of first lvol bdev).
```
 13:48:18	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py destroy_lvol_bdev Lvs0/Lvol0
nvmf_tgt: blobstore.c:185: _spdk_bs_release_cluster: Assertion `spdk_bit_array_get(bs->used_clusters, cluster_num) == true' failed.
```

Will be assessing the how it relates to previously reported issue.

**Comment by tomzawadzki** [comment]
I've since rebased the https://review.spdk.io/gerrit/c/spdk/spdk/+/1111 patch. Yet was unable to reproduce it on latest SPDK, nor its original base (692fce32224970a4da644dffbc959b529fb3783d) from March 2020 on my machine.
