### ISSUE TITLE
SPDK compilation fails on Fedora 30

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#822]
## Steps to Reproduce
1. Clone spdk/spdk
2. (optional) You may need to cherry-pick https://review.gerrithub.io/c/spdk/spdk/+/457923. F30 has new version of pycodestyle which will make check_format.sh fail without these fixes.
3. Run ./autobuild.sh
4. Building SPDK fails:

```
  CC lib/ioat/ioat.o
ioat.c: In function ‘ioat_get_chansts’:
ioat.c:57:26: error: taking address of packed member of ‘struct spdk_ioat_registers’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
   57 |  return spdk_mmio_read_8(&ioat->regs->chansts);
      |                          ^~~~~~~~~~~~~~~~~~~~
ioat.c: In function ‘ioat_write_chancmp’:
ioat.c:63:20: error: taking address of packed member of ‘struct spdk_ioat_registers’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
   63 |  spdk_mmio_write_8(&ioat->regs->chancmp, addr);
      |                    ^~~~~~~~~~~~~~~~~~~~
ioat.c: In function ‘ioat_write_chainaddr’:
ioat.c:69:20: error: taking address of packed member of ‘struct spdk_ioat_registers’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
   69 |  spdk_mmio_write_8(&ioat->regs->chainaddr, addr);
      |                    ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.common.mk:368: ioat.o] Error 1
make[1]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.subdirs.mk:44: ioat] Error 2
make[1]: *** Waiting for unfinished jobs....
  LIB libspdk_nvme.a
make: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.subdirs.mk:44: lib] Error 2
```

## Context (Environment including OS version, SPDK version, etc.)
```
[vagrant@fedora30 spdk]$ uname -a
Linux fedora30.localdomain 5.0.14-300.fc30.x86_64 #1 SMP Thu May 9 10:43:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[vagrant@fedora30 ~]$ gcc --version
gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Current SPDK master commit: ba3adc4367df75113883bc6e653afe01bed86adc

## Additional warnings
I also disabled -werror flag and run autobuild.sh again. Here are some other warnings which might be related:

```
blobstore.c:353:3: warning: Use of memory after it is freed
                memcpy(clusters, blob->active.clusters, blob->active.num_clusters * sizeof(*clusters));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

```
init_grp.c:68:15: warning: Use of memory after it is freed
                if (!strcmp(iname->name, name)) {
                            ^~~~~~~~~~~
init_grp.c:207:15: warning: Use of memory after it is freed
                if (!strcmp(netmask->mask, mask)) {
                            ^~~~~~~~~~~~~
2 warnings generated.
```

```
  CC lib/vhost/rte_vhost_compat.o
rte_vhost_compat.c: In function ‘spdk_extern_vhost_pre_msg_handler’:
rte_vhost_compat.c:114:35: warning: taking address of packed member of ‘struct vhost_user_msg’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  114 |   struct vhost_user_config *cfg = &msg->payload.cfg;
      |                                   ^~~~~~~~~~~~~~~~~
rte_vhost_compat.c:130:35: warning: taking address of packed member of ‘struct vhost_user_msg’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  130 |   struct vhost_user_config *cfg = &msg->payload.cfg;
      |                                   ^~~~~~~~~~~~~~~~~
```

```
In file included from memory.c:39:
In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_eal_memconfig.h:12:
In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_malloc_heap.h:10:
In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_spinlock.h:18:
In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_cycles.h:13:
In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/generic/rte_cycles.h:18:
In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_atomic.h:263:
/home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_atomic_64.h:97:9: warning: Access to field 'cnt' results in a dereference of a null pointer (loaded from variable 'v')
        return v->cnt;
               ^~~~~~
1 warning generated.
```

```
  CC examples/nvme/identify/identify.o
identify.c: In function ‘print_controller’:
identify.c:1273:46: warning: taking address of packed member of ‘struct spdk_nvme_ctrlr_data’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1273 |    const struct spdk_nvme_power_state *psd = &cdata->psd[i];
      |                                              ^~~~~~~~~~~~~~
identify.c:1323:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1323 |   print_uint128_dec(health_page.data_units_read);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~
identify.c:1326:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1326 |   print_uint128_dec(health_page.data_units_written);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
identify.c:1329:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1329 |   print_uint128_dec(health_page.host_read_commands);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
identify.c:1332:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1332 |   print_uint128_dec(health_page.host_write_commands);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
identify.c:1335:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1335 |   print_uint128_dec(health_page.controller_busy_time);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
identify.c:1338:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1338 |   print_uint128_dec(health_page.power_cycles);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~
identify.c:1341:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1341 |   print_uint128_dec(health_page.power_on_hours);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
identify.c:1344:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1344 |   print_uint128_dec(health_page.unsafe_shutdowns);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
identify.c:1347:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1347 |   print_uint128_dec(health_page.media_errors);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~
identify.c:1350:32: warning: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1350 |   print_uint128_dec(health_page.num_error_info_log_entries);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
  CC test/nvme/deallocated_value/deallocated_value.o
deallocated_value.c:398:7: warning: Array access (via field 'write_buf') results in a null pointer dereference
                if (context->write_buf[i]) {
                    ^~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

```
  CC test/unit/lib/blob/blob.c/blob_ut.o
In file included from bdev_ut.c:43:
/home/vagrant/spdk_repo/spdk/lib/bdev/bdev.c:2337:21: warning: Use of memory after it is freed
                if (strcmp(alias, tmp->alias) == 0) {
                                  ^~~~~~~~~~
/home/vagrant/spdk_repo/spdk/lib/bdev/bdev.c:2365:46: warning: Access to field 'bdev' results in a dereference of a null pointer (loaded from variable 'desc')
        return spdk_get_io_channel(__bdev_to_io_dev(desc->bdev));
                                                    ^~~~~~~~~~
/home/vagrant/spdk_repo/spdk/lib/bdev/bdev.c:292:43: note: expanded from macro '__bdev_to_io_dev'
#define __bdev_to_io_dev(bdev)          (((char *)bdev) + 1)
                                                  ^~~~
bdev_ut.c:1371:17: warning: The left operand of '!=' is a garbage value
        CU_ASSERT(desc != NULL);
                  ~~~~ ^
/usr/include/CUnit/CUnit.h:123:30: note: expanded from macro 'CU_ASSERT'
  { CU_assertImplementation((value), __LINE__, #value, __FILE__, "", CU_FALSE); }
                             ^~~~~
bdev_ut.c:1600:17: warning: The left operand of '!=' is a garbage value
        CU_ASSERT(desc != NULL);
                  ~~~~ ^
/usr/include/CUnit/CUnit.h:123:30: note: expanded from macro 'CU_ASSERT'
  { CU_assertImplementation((value), __LINE__, #value, __FILE__, "", CU_FALSE); }
                             ^~~~~
4 warnings generated.
```

```
  CC test/unit/lib/ioat/ioat.c/ioat_ut.o
In file included from ioat_ut.c:36:
/home/vagrant/spdk_repo/spdk/lib/ioat/ioat.c: In function ‘ioat_get_chansts’:
/home/vagrant/spdk_repo/spdk/lib/ioat/ioat.c:57:26: warning: taking address of packed member of ‘struct spdk_ioat_registers’ may result in an unaligned pointer value [-Waddress-of-packed-member]
   57 |  return spdk_mmio_read_8(&ioat->regs->chansts);
      |                          ^~~~~~~~~~~~~~~~~~~~
/home/vagrant/spdk_repo/spdk/lib/ioat/ioat.c: In function ‘ioat_write_chancmp’:
/home/vagrant/spdk_repo/spdk/lib/ioat/ioat.c:63:20: warning: taking address of packed member of ‘struct spdk_ioat_registers’ may result in an unaligned pointer value [-Waddress-of-packed-member]
   63 |  spdk_mmio_write_8(&ioat->regs->chancmp, addr);
      |                    ^~~~~~~~~~~~~~~~~~~~
/home/vagrant/spdk_repo/spdk/lib/ioat/ioat.c: In function ‘ioat_write_chainaddr’:
/home/vagrant/spdk_repo/spdk/lib/ioat/ioat.c:69:20: warning: taking address of packed member of ‘struct spdk_ioat_registers’ may result in an unaligned pointer value [-Waddress-of-packed-member]
   69 |  spdk_mmio_write_8(&ioat->regs->chainaddr, addr);
      |                    ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by darsto** [comment]
There's a patch for rte_vhost_compat.c: https://review.gerrithub.io/c/spdk/spdk/+/457559

Other errors seems to be real issues as well.

**Comment by yidong0635** [comment]
ioat warning: https://review.gerrithub.io/c/spdk/spdk/+/458242

**Comment by karlatec** [comment]
Still failing:

```
identify.c: In function ‘print_controller’:
identify.c:1276:46: error: taking address of packed member of ‘struct spdk_nvme_ctrlr_data’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1276 |    const struct spdk_nvme_power_state *psd = &cdata->psd[i];
      |                                              ^~~~~~~~~~~~~~
identify.c:1326:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1326 |   print_uint128_dec(health_page.data_units_read);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~
identify.c:1329:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1329 |   print_uint128_dec(health_page.data_units_written);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
identify.c:1332:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1332 |   print_uint128_dec(health_page.host_read_commands);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
identify.c:1335:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1335 |   print_uint128_dec(health_page.host_write_commands);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
identify.c:1338:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1338 |   print_uint128_dec(health_page.controller_busy_time);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
identify.c:1341:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1341 |   print_uint128_dec(health_page.power_cycles);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~
identify.c:1344:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1344 |   print_uint128_dec(health_page.power_on_hours);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~
identify.c:1347:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1347 |   print_uint128_dec(health_page.unsafe_shutdowns);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
identify.c:1350:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1350 |   print_uint128_dec(health_page.media_errors);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~
identify.c:1353:32: error: taking address of packed member of ‘struct spdk_nvme_health_information_page’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1353 |   print_uint128_dec(health_page.num_error_info_log_entries);
      |                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by darsto** [comment]
Bug scrub: as for ioat.c case:

Ben suggests to drop the packed attribute and add a STATIC_ASSERT to check struct size. The gcc error is just too pessimistic, there's no actual error.

**Comment by darsto** [comment]
@tomzawadzki to look at the blobstore case

@Comphix  there's one issue on iscsi, can you take a look?

```
init_grp.c:68:15: warning: Use of memory after it is freed
                if (!strcmp(iname->name, name)) {
                            ^~~~~~~~~~~
init_grp.c:207:15: warning: Use of memory after it is freed
                if (!strcmp(netmask->mask, mask)) {
                            ^~~~~~~~~~~~~
2 warnings generated.
```

**Comment by yidong0635** [comment]
For now, https://github.com/openucx/ucx/pull/3125 , this website indicates method to resolve this kind of warning.
apply this to identify as well.

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/458535, if you prefer to other solution, please tell me.

**Comment by karlatec** [comment]
@yidong0635 Thanks, this fixes the identify.c issue for me!

Compliation still has multiple warnings, both related to DPDK and SPDK and finally fails due to scan-build errors.

Attaching STDERR output from build and scan-build report as well.

[error.log](https://github.com/spdk/spdk/files/3304731/error.log)
[scan-build.zip](https://github.com/spdk/spdk/files/3304733/scan-build.zip)

**Comment by yidong0635** [comment]
use ./scripts/pkgdep.sh always failed. I can't simulate other issues.
DPDP maybe the same issue,  let Darek to update.

**Comment by yidong0635** [comment]
use following commands can solve update failures.
dnf clean all
dnf update
dnf install gcc

**Comment by karlatec** [comment]
@yidong0635 Sorry, I don't follow. Why are we discussing failing pkgdep.sh and dnf update failures?

**Comment by yidong0635** [comment]
@karlatec  this just a record for simulating you issue, it's the milestone to setup fedora30, for further, 
our update.sh should be changed. this is a issue.

**Comment by karlatec** [comment]
@yidong0635 I didn't have any issues with pkgdep.sh or vm_setup.sh.
Also - that's not really related to this issue report, so if there's an issue with the scripts then we should probably start a new thread.

**Comment by yidong0635** [comment]
there are so many similar issues :
init_grp.c ,https://review.gerrithub.io/c/spdk/spdk/+/458715
that strict checking , maybe some need add assert is only. please tell me if you perfer.

**Comment by yidong0635** [comment]
some of  these issues may failed at unit test. so not only just make this compiling pass, need to dig into details.

**Comment by wanghailiangx** [comment]
Fixing freed memory warning about blob/blobstore.c.
https://review.gerrithub.io/c/spdk/spdk/+/459411
```
blobstore.c:354:4: warning: Use of memory after it is freed
                        memcpy(clusters, blob->active.clusters, blob->active.num_clusters * sizeof(*clusters));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by wanghailiangx** [comment]
test/dif_ut: fix a warning of iov_base garbage value 
https://review.gerrithub.io/c/spdk/spdk/+/459712
```  
LINK test/unit/lib/ftl/ftl_io.c/ftl_io_ut
dif_ut.c:151:24: warning: The left operand of '==' is a garbage value
        return (iov->iov_base == iov_base && iov->iov_len == iov_len);
                ~~~~~~~~~~~~~ ^
1 warning generated.
```

**Comment by tomzawadzki** [comment]
Added some fixes for scan-build issues:
- [ut/nvmf: fixed scan-build error by initializing command and response](https://review.gerrithub.io/c/spdk/spdk/+/459758)
- [ut/lvol: fixed scan-build error on spdk_bs_init](https://review.gerrithub.io/c/spdk/spdk/+/459756)
- [test/ut: initialize spdk_bdev_desc to NULL](https://review.gerrithub.io/c/spdk/spdk/+/459755)

And tried to address bulk of unit tests scan-build failures by replacing usual asserts with *_FATAL versions. It changes the general approach for UT by stopping on first failure.
- [ut/cunit: added missing semicolon on CU_ASSERT macros](https://review.gerrithub.io/c/spdk/spdk/+/459760)
- [ut/cunit: redefine asserts to *_FATAL variants](https://review.gerrithub.io/c/spdk/spdk/+/459761)

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/459927: 
```
In file included from rdma_ut.c:37:
/home/vagrant/spdk_repo/spdk/lib/nvmf/rdma.c:1542:44: warning: 1st function call argument is an uninitialized value
                        wr->sg_list[i].lkey = ((struct ibv_mr *)spdk_mem_map_translate(device->map,
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vagrant/spdk_repo/spdk/lib/nvmf/rdma.c:1545:26: warning: 1st function call argument is an uninitialized value
                        wr->sg_list[i].lkey = spdk_mem_map_translate(device->map,
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/459939 :
 ```
bdev_ut.c:1486:2: warning: Potential leak of memory pointed to by 'histogram'
            poll_threads();
            ^~~~~~~~~~~~~~
    1 warning generated.

```

**Comment by wanghailiangx** [comment]
1. bdev/raid: fix a warning of freed memory
https://review.gerrithub.io/c/spdk/spdk/+/460069
In file included from bdev_raid_ut.c:38:
```
spdk/lib/bdev/raid/bdev_raid.c:325:11: warning: Use of memory after it is freed
                                             raid_ch->base_channel[pd_idx],
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2. test/bdev_raid_ut: fix a warning of a null pointer dereference
https://review.gerrithub.io/c/spdk/spdk/+/460094
```
bdev_raid_ut.c:659:13: warning: Array access (via field 'base_channel') results in a null pointer dereference
                CU_ASSERT(ch_ctx->base_channel[index] == g_io_output[index].ch);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
bdev_raid_ut.c:2181:14: warning: Array access (via field 'base_channel') results in a null pointer dereference
                CU_ASSERT(ch_ctx->base_channel[j] == (void *)0x1);
                          ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by yidong0635** [comment]
missed this one： https://review.gerrithub.io/c/spdk/spdk/+/459529

**Comment by darsto** [comment]
@karlatec could you check the current state?

**Comment by karlatec** [comment]
Retested. Build run with:
```
./autobuild.sh ~/autorun-spdk.conf
```

Conf contents:
```
[vagrant@fedora30 spdk]$ cat ~/autorun-spdk.conf
SPDK_BUILD_DOC=0
SPDK_BUILD_SHARED_OBJECT=1
SPDK_RUN_CHECK_FORMAT=0
SPDK_RUN_SCANBUILD=1
SPDK_RUN_VALGRIND=0
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_ISAL=1
SPDK_TEST_ISCSI=1
SPDK_TEST_ISCSI_INITIATOR=1
SPDK_TEST_NVME=1
SPDK_TEST_NVME_CLI=1
SPDK_TEST_NVMF=1
SPDK_TEST_NVMF_TRANSPORT="rdma"
SPDK_TEST_RBD=1
SPDK_TEST_VHOST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_IOAT=1
SPDK_TEST_EVENT=1
SPDK_TEST_BLOBFS=1
SPDK_TEST_VHOST_INIT=1
SPDK_TEST_PMDK=1
SPDK_TEST_LVOL=1
SPDK_TEST_JSON=1
SPDK_TEST_REDUCE=1
SPDK_TEST_VPP=0
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
SPDK_RUN_INSTALLED_DPDK=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_FTL=1
SPDK_TEST_BDEV_FTL=1
SPDK_TEST_OCF=1
SPDK_TEST_FTL_EXTENDED=1
SPDK_TEST_VMD=1
```

Result: 21 scanbuild issues. See attached scanbuild report.
[scan-build.tar.gz](https://github.com/spdk/spdk/files/3405770/scan-build.tar.gz)

**Comment by yidong0635** [comment]
add three patch here;
https://review.gerrithub.io/c/spdk/spdk/+/462592
https://review.gerrithub.io/c/spdk/spdk/+/462574
https://review.gerrithub.io/c/spdk/spdk/+/462576

there are two issues in dpdk:
```
spdk/dpdk/build/include/rte_atomic_64.h:97:9: warning: Access to field 'cnt' results in a dereference of a null pointer (loaded from variable 'v')
        return v->cnt;
               ^~~~~~
1
In file included from vbdev_crypto.c:46:
spdk/dpdk/build/include/rte_crypto.h:136:11: warning: Dereference of null pointer
        op->type = type;
        ~~~~~~~~~^~~~~~
1 warning generated.
  LIB libspdk_bdev_crypto.a
```
```
spdk/test/common/lib/test_env.c:103:2: warning: Use of memory after it is freed
        HANDLE_RETURN_MOCK(spdk_zmalloc);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/yidong/spdk/include/spdk_internal/mock.h:106:3: note: expanded from macro 'HANDLE_RETURN_MOCK'
                return ut_ ## fn; \
                ^~~~~~~~~~~~~~~~
1 warning generated.
  LINK test/unit/lib/nvme/nvme_qpair.c/nvme_qpair_ut
vbdev_lvol_ut.c:97:7: warning: Null pointer passed as an argument to a 'nonnull' parameter
                if (strncmp(alias, tmp->alias, SPDK_LVOL_NAME_MAX) == 0) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
after apply darek's tailq_remove work around. this issue still occured, will take a look next week.
```
bdev_ut.c:1486:2: warning: Potential leak of memory pointed to by 'histogram'
        poll_threads();
        ^~~~~~~~~~~~~~
1 warning generated.
```
blobstore.c need to verify with hailiang.

In all left 6 issues.

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/462598
for vbdev_lvol_ut.c:97:7: warning: Null pointer passed as an argument to a 'nonnull' parameter
                if (strncmp(alias, tmp->alias, SPDK_LVOL_NAME_MAX) == 0) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/462789

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/462822 
for :
```
spdk/test/common/lib/test_env.c:103:2: warning: Use of memory after it is freed
        HANDLE_RETURN_MOCK(spdk_zmalloc);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/yidong/spdk/include/spdk_internal/mock.h:106:3: note: expanded from macro 'HANDLE_RETURN_MOCK'
                return ut_ ## fn; \
                ^~~~~~~~~~~~~~~~
1 warning generated.
  LINK test/unit/lib/nvme/nvme_qpair.c/nvme_qpair_ut
```

**Comment by darsto** [comment]
After applying a few patches from gerrithub:
```
$ make clean -j4; scan-build --status-bugs make -j4
<SNIP>
scan-build: Removing directory '/tmp/scan-build-2019-07-22-135850-2977-1' because it contains no reports.
scan-build: No bugs found.
```


System:
```
$ dnf info clang-analyzer
Fedora Modular 30 - x86_64                                                                                                                                                            14 kB/s |  24 kB     00:01
Fedora Modular 30 - x86_64 - Updates                                                                                                                                                  14 kB/s |  22 kB     00:01
Fedora 30 - x86_64 - Updates                                                                                                                                                          13 kB/s |  22 kB     00:01
Fedora 30 - x86_64                                                                                                                                                                    14 kB/s |  24 kB     00:01
Installed Packages
Name         : clang-analyzer
Version      : 8.0.0
Release      : 1.fc30
Architecture : noarch
Size         : 158 k
Source       : clang-8.0.0-1.fc30.src.rpm
```

```
$ uname -a
Linux cloud-00 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ git log --oneline
4368e0dd0 (HEAD -> master) ut/nvme: add missing probe_ctx.init_ctrlrs tailq initialization
70acf973b ut/ftl_reloc: silence scan-build errors
2daaa20f9 env_dpdk/memory: silence scan-build errors
430cf3923 blobstore: don't realloc any memory under scan-build
6af394750 queue: redefine TAILQ_REMOVE for scan-build
77fa5a8c3 bdev/vbdev_lvol: Fix scanbuild error about Null poniter parameter.
5c5f47ee4 compress: Fix scanbuild error about dereference of null pointer.
00d09473f compress: Clear some simple scanbuild errors.
9cfe7046e nvme_qpair_ut: Fix scanbuild warning about using freed memory.
c878841e6 bdev: Fix warning about potenial memory leak about histogram.
38889bbfd (origin/master, origin/HEAD) test/ftl: reduce the number of required parallel units
```

Most of those patches are scattered around gerrithub, I had to cherry-pick all of them.

**Comment by darsto** [comment]
Older scan-build version on our CI required a few more patches, but eventually we got it fixed, top here: https://review.gerrithub.io/c/spdk/spdk/+/459285

```
queue: redefine TAILQ_REMOVE for scan-build
crypto: silence scan-build null dereference false positive
ut/nvme: silence scan-build warnings about null dereference
ut/bdev: silence scan-build warnings about garbage value comparison
ut/bdev: silence scan-build warnings about histogram memory leaks
```

This passes scan-build on the CI as well as fedora-30.

**Comment by jimharris** [comment]
Bug filed with LLVM for the TAILQ_REMOVE issue:  https://bugs.llvm.org/show_bug.cgi?id=42780

**Comment by darsto** [comment]
All fixes merged. Confirmed latest master works on fedora 30. Thanks everyone!

**Comment by jimharris** [comment]
I agree - these are going to pop up more in the future.  I updated my Ubuntu system to 19.04 and get 70(!!!) scan-build errors including the crypto one you originally coded a workaround for:

https://review.gerrithub.io/c/spdk/spdk/+/463232

Closing this issue is fine but we probably need to be more aggressive about filing LLVM issues and getting ahead of bugs that scan-build finds.  I don't mind being the LLVM bug reporter.

**Comment by yidong0635** [comment]
this one  still exist: 
 LIB libspdk_bdev_virtio.a
In file included from vbdev_crypto.c:46:
/root/yidong/spdk/dpdk/build/include/rte_crypto.h:136:11: warning: Dereference of null pointer
        op->type = type;
        ~~~~~~~~~^~~~~~
1 warning generated.
  LIB libspdk_bdev_crypto.a
  LIB libspdk_ftl.a

**Comment by peluse** [comment]
that's in DPDK

**Comment by jimharris** [comment]
It is in a DPDK header file.  But the scan-build error happens when we build an SPDK module (which includes that header file).  I see this on my Ubuntu 19.04 system as well.

I think since SPDK compilation passes on Fedora 30 now, we should keep this issue closed and file a new issue for any other scan-build issues with scan-build 8.0.
